import {test,expect,type Page,type APIResponse,type Locator} from "@playwright/test";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {createRegionWorkspace,workspaceTestRuntime} from "./workspace-session";

const root=path.resolve(__dirname,"../../..");const {api,python,dataDir}=workspaceTestRuntime();const evidence=process.env.CYTELLECT_SCREENSHOT_DIR;
const policy={version:"1.0.0",mode:"area_only"};
async function json(response:Pick<APIResponse,"ok"|"json">){expect(response.ok()).toBeTruthy();return response.json();}
async function mutation(page:Page,suffix:string,action:()=>Promise<void>){const result=page.waitForResponse(response=>response.url().includes(suffix)&&response.request().method()==="POST");await action();return json(await result);}
async function waitJob(page:Page,id:string){await expect.poll(async()=>{const job=await json(await page.request.get(`${api}/v1/jobs/${id}`));if(["failed","cancelled"].includes(job.state))throw Error(job.error);return job.state;},{timeout:120000,intervals:[500,1000]}).toBe("succeeded");}
async function open(details:Locator){if(!await details.evaluate(element=>(element as HTMLDetailsElement).open))await details.locator(":scope>summary").click();return details;}
async function polygon(page:Page,value:string){await open(page.locator("details").filter({has:page.locator(":scope>summary",{hasText:"座標から多角形を指定"})}));await page.getByRole("textbox",{name:"頂点（x,y を空白または改行で区切る）",exact:true}).fill(value);await page.getByRole("button",{name:"座標を反映",exact:true}).click();}
async function review(page:Page){await page.getByLabel("領域と面積、失敗・除外理由を確認しました。",{exact:true}).check();await mutation(page,"/review",()=>page.getByRole("button",{name:"品質確認を完了",exact:true}).click());}
async function shot(page:Page,name:string){if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.screenshot({path:path.join(evidence,name),fullPage:true});}}
async function preview(page:Page){await expect.poll(()=>page.getByTestId("image-canvas").locator("canvas").first().evaluate(element=>{const canvas=element as HTMLCanvasElement,data=canvas.getContext("2d")!.getImageData(0,0,canvas.width,canvas.height).data;let opaque=0,total=0;for(let i=3;i<data.length;i+=64){total++;if(data[i]>250)opaque++;}return opaque/total;})).toBeGreaterThan(.3);}
function scratch(){if(!dataDir)throw Error("Isolated data directory required");return fs.mkdtempSync(path.join(dataDir,"area-ui-"));}
async function bundle(page:Page,workspaceId:string,fixture:string,name:string){
 await page.getByRole("button",{name:/04 保存と履歴/}).click();await expect(page.getByLabel("原画像もZIPへ含める",{exact:true})).not.toBeChecked();
 const exported=await mutation(page,"/export?",()=>page.getByRole("button",{name:"解析パッケージを生成",exact:true}).click());await waitJob(page,exported.job_id);
 const pending=page.waitForEvent("download");await page.getByRole("button",{name:"ZIPを保存 ↓",exact:true}).first().click();const zip=await pending;expect(await zip.failure()).toBeNull();const output=path.join(evidence||fixture,`${name}.zip`);await zip.saveAs(output);
 return JSON.parse(execFileSync(python,["-c",`import sys,json,zipfile,hashlib
from pathlib import Path
from cytellect_analysis.region_exports import replay_region_bundle
archive=Path(sys.argv[1]);bundle=archive.parent/(archive.stem+'-unpacked');out=archive.parent/(archive.stem+'-replay')
assert not bundle.exists() and not out.exists()
with zipfile.ZipFile(archive) as z:
 m=json.loads(z.read('manifest.json'));assert m['format']=='cytellect-region-reproducibility/2';assert m['raw_included'] is False
 assert not any(n.startswith('raw/') for n in z.namelist());assert not any('background' in n and n.endswith('.npy') for n in z.namelist())
 assert all(hashlib.sha256(z.read(p)).hexdigest()==h for p,h in m['files'].items());z.extractall(bundle)
r=replay_region_bundle(bundle,Path(sys.argv[2]),out)
assert r['matched_saved_measurements']
print(json.dumps({'format':m['format'],'verified_files':len(m['files']),'raw_included':False,'background_arrays':0,'replay':r}))`,output,path.join(dataDir!,"workspaces",workspaceId,"fields")],{encoding:"utf8"}));
}

test("public-image area-only workflow skips backgrounds and preserves masks through mode changes and source export",async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const fixture=scratch();
 const raw=path.join(root,"fixtures/public/bbbc013/A01-gfp.tif"),dna=path.join(root,"fixtures/public/bbbc013/A01-dapi.tif"),labels=path.join(fixture,"labels.tif");
 // Public pixel intensities are unchanged; sparse rectangles are artificial UI/area references, not detected nuclei.
 execFileSync(python,["-c","import sys,numpy as np,tifffile;a=tifffile.imread(sys.argv[1]);m=np.zeros(a.shape,dtype=np.uint32);m[25:27,25:28]=7;m[50:53,50:54]=19;tifffile.imwrite(sys.argv[2],m)",raw,labels]);
 const workspace=await createRegionWorkspace(page,"Public image area workflow");
 for(const [i,label,file] of [[1,"FKHR-EGFP",raw],[2,"DRAQ",dna]] as const){if(i===2)await page.getByRole("button",{name:"チャンネルを追加",exact:true}).click();await page.getByLabel(`チャンネル ${i} の表示名`,{exact:true}).fill(label);await page.getByLabel(`チャンネル ${i} の画像`,{exact:true}).setInputFiles(file);await page.getByLabel(`チャンネル ${i} の画像と表示名の対応を確認しました。`,{exact:true}).check();}
 await page.getByText("画素サイズと領域マスク",{exact:true}).click();await page.getByLabel("領域マスクを取り込む",{exact:true}).check();await page.getByLabel("整数ラベル TIFF",{exact:true}).setInputFiles(labels);
 const first=await mutation(page,"/region-fields",()=>page.getByRole("button",{name:"この視野を登録",exact:true}).click());
 await page.getByLabel("測定する量",{exact:true}).selectOption("area_only");await expect(page.getByRole("button",{name:"背景",exact:true})).toHaveCount(0);await expect(page.getByText("▱ 背景",{exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"この視野で始める",exact:true})).toBeEnabled();
 let initialRequest:Record<string,unknown>|undefined;page.on("request",request=>{if(request.method()==="POST"&&new URL(request.url()).pathname.endsWith("/region-analyses"))initialRequest=request.postDataJSON();});
 const initial=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"この視野で始める",exact:true}).click());await waitJob(page,initial.job_id);expect(initialRequest).toMatchObject({measurement:policy,backgrounds:{}});
 const report=await json(await page.request.get(`${api}/v1/revisions/${initial.revision_id}/region-measurements`));expect(report.protocol_version).toBe("2.0.0");expect(report.field_tables[first.id].rows.map((row:{area_px:number})=>row.area_px)).toEqual([6,6,12,12]);
 for(const row of report.field_tables[first.id].rows){for(const key of ["mean","median","integrated","mean_corrected","median_corrected","integrated_corrected","storage_limit_fraction","acquisition_saturation_fraction"])expect(row[key]).toBeNull();expect(row.intensity_missing_reason).toBe("not_requested");expect(row.area_um2).toBeNull();}
 await expect(page.getByRole("columnheader",{name:"平均（原値）",exact:true})).toHaveCount(0);await expect(page.getByText(/保存済みの測定：面積のみ/)).toBeVisible();await expect(page.getByText("測定条件",{exact:true})).toBeVisible();await preview(page);
 await page.getByLabel("選択した領域ID",{exact:true}).fill("7");await page.getByRole("button",{name:"輪郭修正",exact:true}).click();await polygon(page,"25,25 29,25 29,27 25,27");await expect(page.getByLabel("測定する量",{exact:true})).toBeDisabled();
 const edited=await mutation(page,"/region-edits",()=>page.getByRole("button",{name:/^領域を保存・再測定/}).click());await waitJob(page,edited.job_id);const savedMasks=await json(await page.request.get(`${api}/v1/revisions/${edited.revision_id}/region-masks?field_id=${first.id}`));
 const headers={Origin:new URL(page.url()).origin,"X-Cytellect-Request":"1"};
 const second=await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-fields`,{headers,multipart:{specification:JSON.stringify({version:"1.0.0",channels:first.image_info.channels}),ch0:{name:"second-signal.tif",mimeType:"image/tiff",buffer:fs.readFileSync(raw)},ch1:{name:"second-nuclear.tif",mimeType:"image/tiff",buffer:fs.readFileSync(dna)},labels:{name:"second-labels.tif",mimeType:"image/tiff",buffer:fs.readFileSync(labels)}}}));
 await page.reload();await page.getByRole("button",{name:/Public image area workflow/}).click();await expect(page.getByLabel("測定する量",{exact:true})).toHaveValue("area_only");
 const batch=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"領域を保持して全視野を測定",exact:true}).click());await waitJob(page,batch.job_id);expect(initialRequest).toMatchObject({measurement:policy,backgrounds:{},reuse_revision:edited.revision_id});expect(await json(await page.request.get(`${api}/v1/revisions/${batch.revision_id}/region-masks?field_id=${first.id}`))).toEqual(savedMasks);
 const batchReport=await json(await page.request.get(`${api}/v1/revisions/${batch.revision_id}/region-measurements`));expect(Object.keys(batchReport.field_tables)).toHaveLength(2);expect(batchReport.field_tables[second.id].rows).toHaveLength(4);await review(page);
 await shot(page,"area-only-workbench-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"area-only-workbench-mobile.png");await page.setViewportSize({width:1440,height:1000});
 await page.getByRole("button",{name:/02 図の出力/}).click();expect(await page.getByLabel("表示する測定値",{exact:true}).locator("option").evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value))).toEqual(["","area_px"]);
 await page.getByLabel("表示する測定値",{exact:true}).selectOption("area_px");const described=await mutation(page,"/descriptive",()=>page.getByRole("button",{name:"分布図を作成",exact:true}).click());await waitJob(page,described.job_id);const describedResult=await json(await page.request.get(`${api}/v1/jobs/${described.job_id}/result`));expect(describedResult.counts.observations).toBe(4);expect(describedResult.spec.selection).toMatchObject({channel_id:null,metric:"area_px"});
 const figure=page.getByAltText("領域の測定値と視野内中央値の分布図",{exact:true});await expect(figure).toBeVisible();await expect.poll(()=>figure.evaluate(image=>(image as HTMLImageElement).complete&&(image as HTMLImageElement).naturalWidth>0)).toBe(true);
 await open(page.locator("details").filter({has:page.locator(":scope>summary",{hasText:"図に使った測定値"})}));await page.getByRole("button",{name:/図の視野 \d+ 領域 7 を画像で確認/}).first().click();await expect(page.getByRole("status").filter({hasText:"図に記録された領域 7"})).toContainText("面積測定にはチャンネルを使用していません");await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("7");await preview(page);
 const exported=await bundle(page,workspace.id,fixture,"area-public");
 await page.getByRole("button",{name:/01 画像と領域/}).click();await page.getByLabel("測定する量",{exact:true}).selectOption("area_and_intensity");await expect(page.getByText("▱ 背景",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"測定する量を変更して再測定",exact:true})).toBeDisabled();
 // Returning to intensity mode must require fresh, explicit background confirmation for every actual field/channel.
 for(let i=0;i<2;i++){await page.locator('[class*="fieldSidebar"]').getByRole("button").nth(i).click();for(const label of ["FKHR-EGFP","DRAQ"]){await page.getByRole("button",{name:label,exact:true}).click();await page.getByRole("button",{name:"背景",exact:true}).click();await polygon(page,"0,0 15,0 15,15 0,15");await page.getByRole("button",{name:/^背景を確定/}).click();}}
 const corrected=await mutation(page,"/region-reconfigure",()=>page.getByRole("button",{name:"測定する量を変更して再測定",exact:true}).click());await waitJob(page,corrected.job_id);const correctedReport=await json(await page.request.get(`${api}/v1/revisions/${corrected.revision_id}/region-measurements`));expect(correctedReport.protocol_version).toBe("1.0.0");expect(correctedReport.field_tables[first.id].rows.every((row:{mean:number|null})=>typeof row.mean==="number")).toBe(true);expect(await json(await page.request.get(`${api}/v1/revisions/${corrected.revision_id}/region-masks?field_id=${first.id}`))).toEqual(savedMasks);
 await expect(page.getByLabel("領域、チャンネルごとの背景、失敗・除外理由を確認しました。",{exact:true})).not.toBeChecked();await page.getByLabel("測定する量",{exact:true}).selectOption("area_only");const returned=await mutation(page,"/region-reconfigure",()=>page.getByRole("button",{name:"測定する量を変更して再測定",exact:true}).click());await waitJob(page,returned.job_id);await page.reload();await page.getByRole("button",{name:/Public image area workflow/}).click();await expect(page.getByRole("button",{name:"背景",exact:true})).toHaveCount(0);await expect(page.getByLabel("領域と面積、失敗・除外理由を確認しました。",{exact:true})).not.toBeChecked();
 const revisions=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}/revisions`));expect(revisions.find((r:{id:string})=>r.id===corrected.revision_id).config).not.toHaveProperty("measurement");expect(revisions.find((r:{id:string})=>r.id===returned.revision_id).config).toMatchObject({measurement:policy,backgrounds:{}});expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"area-public-receipt.json"),JSON.stringify({scope:"BBBC013 unchanged published pixels, artificial sparse-label area/UI fixture; no segmentation accuracy or biological replication claim",initialAreaPixels:[6,12],channelNeutralObservationCount:4,allIntensityAndSaturationNull:true,correctedMaskReuseExact:true,freshBackgroundsRequiredOnIntensityReturn:true,areaHistoryClearsBackgrounds:true,exported,pageErrors:errors},null,2));
});

test("calibrated area-only comparisons retain declared units and source hierarchy without fluorescence evidence",async({page})=>{
 test.setTimeout(240000);const fixture=scratch();const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const workspace=await createRegionWorkspace(page,"Artificial calibrated area comparison");
 execFileSync(python,["-c",`import sys,numpy as np,tifffile
from pathlib import Path
p=Path(sys.argv[1]);tifffile.imwrite(p/'image.tif',np.full((64,64),100,dtype=np.uint16))
for k in range(1,5):
 m=np.zeros((64,64),dtype=np.uint32);m[10:12,10:10+3*k]=7;m[30:33,30:30+4*k]=19;tifffile.imwrite(p/f'labels-{k}.tif',m)`,fixture]);
 const fields:{id:string}[]=[];const headers={Origin:new URL(page.url()).origin,"X-Cytellect-Request":"1"};
 for(let i=0;i<4;i++)fields.push(await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-fields`,{headers,multipart:{specification:JSON.stringify({version:"1.0.0",channels:[{channel_id:"reference",label:"人工画像",stain:null,identity_confirmed:true}],calibration:{pixel_size_x_um:.2,pixel_size_y_um:.3,confirmed:true},metadata:{condition:i<2?"A":"B",sample:`sample-${i+1}`,experimental_unit:`unit-${i+1}`,acquisition_date:"artificial-batch",pair:null,repeat_length:null}}),ch0:{name:"image.tif",mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,"image.tif"))},labels:{name:`labels-${i+1}.tif`,mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,`labels-${i+1}.tif`))}}})));
 await page.reload();await page.getByRole("button",{name:/Artificial calibrated area comparison/}).click();await page.getByLabel("測定する量",{exact:true}).selectOption("area_only");
 const initial=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"全視野の領域を用意",exact:true}).click());await waitJob(page,initial.job_id);await review(page);await page.getByRole("button",{name:/03 統計解析/}).click();
 const metricSelect=page.getByLabel("比較する測定値",{exact:true});expect(await metricSelect.locator("option").evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value))).toEqual(["","area_px","area_um2"]);await expect(metricSelect.locator('option[value=""]')).toHaveJSProperty('disabled',true);await metricSelect.selectOption("area_um2");await expect(page.getByLabel("実験デザイン",{exact:true})).toHaveValue("");await expect(page.getByRole("button",{name:"比較と図を作成",exact:true})).toBeDisabled();
 await page.getByLabel("実験デザイン",{exact:true}).selectOption("independent");await page.getByLabel("独立実験単位の定義",{exact:true}).fill("Artificial software-validation units; no biological replication");await page.getByLabel("A",{exact:true}).check();await page.getByLabel("B",{exact:true}).check();await page.getByLabel("対照群",{exact:true}).selectOption("A");await page.getByLabel("独立性と、必要な対応関係を実験記録で確認しました。",{exact:true}).check();await page.getByLabel("領域定義・採取方法と面積の尺度を比較できると確認しました。",{exact:true}).check();await page.getByLabel("除外・欠測と比較対象を確認しました。",{exact:true}).check();
 const compared=await mutation(page,"/region-comparisons",()=>page.getByRole("button",{name:"比較と図を作成",exact:true}).click());await waitJob(page,compared.job_id);const result=await json(await page.request.get(`${api}/v1/jobs/${compared.job_id}/region-comparison`));expect(result.channel).toBeNull();expect(result.spec.selection).toMatchObject({metric:"area_um2",channel_id:null});expect(result.counts.map((row:{experimental_units:number})=>row.experimental_units)).toEqual([2,2]);expect(result.comparisons[0].estimate).toBeCloseTo(-1.08,12);
 const plot=page.getByAltText("実験単位の集計値と群間比較の図",{exact:true});await expect(plot).toBeVisible();await expect.poll(()=>plot.evaluate(image=>(image as HTMLImageElement).complete&&(image as HTMLImageElement).naturalWidth>0)).toBe(true);
 const hierarchy=page.getByLabel("実験単位から視野への集計",{exact:true});await open(hierarchy.getByLabel("A 実験単位 unit-1",{exact:true}));await open(hierarchy.getByLabel("A 実験単位 unit-1 試料 sample-1",{exact:true}));await expect(hierarchy.getByLabel("集計の視野 1",{exact:true})).toContainText("0.54");
 await shot(page,"area-only-comparison-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"area-only-comparison-mobile.png");await page.setViewportSize({width:1440,height:1000});
 await hierarchy.getByRole("button",{name:"集計の視野 1 を保存済み画像で確認",exact:true}).click();await expect(page.getByLabel("保存済み比較の視野",{exact:true})).toContainText("面積測定にはチャンネルを使用していません");await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("");await preview(page);
 const exported=await bundle(page,workspace.id,fixture,"area-comparison");expect(exported.replay.matched_saved_comparisons).toBe(true);expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"area-comparison-receipt.json"),JSON.stringify({scope:"Artificial constant images and known masks; software/inference integration only, no biological group comparison",calibration:{x:.2,y:.3},areaPerFieldPixels:[[6,12],[12,24],[18,36],[24,48]],unitValuesUm2:[.54,1.08,1.62,2.16],estimate:-1.08,independentUnits:[2,2],channel:null,backgroundsAbsent:true,sourceHierarchy:true,exported,pageErrors:errors},null,2));
});

test("area planning2.1 proposes a mode but actual inputs and changed measurement remain explicitly reviewed",async({page})=>{
 test.setTimeout(180000);const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));await createRegionWorkspace(page,"Area planning bootstrap");await page.getByRole("button",{name:"← 作業一覧",exact:true}).click();await page.getByRole("link",{name:"解析設定を開く",exact:true}).click();
 await page.getByLabel("測定項目",{exact:true}).selectOption("area");await page.getByLabel("測定対象",{exact:true}).selectOption("custom");await page.getByLabel("領域の作成方法",{exact:true}).selectOption("manual");await page.getByLabel("測定に使う画像",{exact:true}).selectOption("grayscale-2d");await page.getByLabel("解析内容",{exact:true}).selectOption("descriptive");
 await expect(page.getByLabel("画像内の背景領域",{exact:true})).toHaveCount(0);await expect(page.getByText("面積のみの測定では、背景ROIは不要です。",{exact:true})).toBeVisible();await page.getByRole("radio",{name:"手動領域の面積・輝度",exact:true}).check();await page.getByRole("button",{name:/この設定で作成/}).click();await page.getByLabel("作業名",{exact:true}).fill("Adopted area-only plan");
 const workspace=await mutation(page,"/v1/workspaces",()=>page.getByRole("button",{name:"作業を作成",exact:true}).click());expect(workspace.analysis_plan.input.version).toBe("2.1.0");expect(workspace.analysis_plan.input.answers.background).toBe("unknown");expect(workspace.analysis_plan.decision.candidates[0].measurement).toEqual(policy);
 await page.getByLabel("チャンネル 1 の表示名",{exact:true}).fill("DRAQ");await page.getByLabel("チャンネル 1 の画像",{exact:true}).setInputFiles(path.join(root,"fixtures/public/bbbc013/A01-dapi.tif"));await expect(page.getByLabel("チャンネル 1 の画像と表示名の対応を確認しました。",{exact:true})).not.toBeChecked();await page.getByLabel("チャンネル 1 の画像と表示名の対応を確認しました。",{exact:true}).check();await mutation(page,"/region-fields",()=>page.getByRole("button",{name:"この視野を登録",exact:true}).click());
 await expect(page.getByLabel("測定する量",{exact:true})).toHaveValue("area_only");await expect(page.getByLabel("計画に対応する面積の単位",{exact:true})).toHaveValue("");await expect(page.getByRole("button",{name:"この視野で始める",exact:true})).toBeDisabled();await page.getByLabel("計画に対応する面積の単位",{exact:true}).selectOption("area_px");
 const initial=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"この視野で始める",exact:true}).click());await waitJob(page,initial.job_id);await expect(page.getByLabel("領域と面積、失敗・除外理由を確認しました。",{exact:true})).not.toBeChecked();
 const initialRevisions=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}/revisions`));expect(initialRevisions.find((r:{id:string})=>r.id===initial.revision_id).config.plan_resolution).toMatchObject({version:"1.1.0",measurement:policy,metric:"area_px",channel_id:null,changes_acknowledged:false});
 await page.getByLabel("測定する量",{exact:true}).selectOption("area_and_intensity");await expect(page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true})).not.toBeChecked();await expect(page.getByRole("button",{name:"測定する量を変更して再測定",exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"背景",exact:true}).click();await polygon(page,"0,0 15,0 15,15 0,15");await page.getByRole("button",{name:/^背景を確定/}).click();await expect(page.getByRole("button",{name:"測定する量を変更して再測定",exact:true})).toBeDisabled();
 await page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true}).check();await page.getByLabel("計画に対応する実チャンネルと指標",{exact:true}).selectOption("channel-1-mean_corrected");await expect(page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true})).not.toBeChecked();await page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true}).check();
 const changed=await mutation(page,"/region-reconfigure",()=>page.getByRole("button",{name:"測定する量を変更して再測定",exact:true}).click());await waitJob(page,changed.job_id);const revisions=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}/revisions`));const latest=revisions.find((r:{id:string})=>r.id===changed.revision_id);expect(latest.reviewed).toBe(false);expect(latest.config).not.toHaveProperty("measurement");expect(latest.config.plan_resolution).toMatchObject({version:"1.1.0",measurement:null,metric:"mean_corrected",channel_id:"channel-1",changes_acknowledged:true});
 await expect(page.getByLabel("領域、チャンネルごとの背景、失敗・除外理由を確認しました。",{exact:true})).not.toBeChecked();await shot(page,"area-plan-mode-change-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"area-plan-mode-change-mobile.png");expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"area-plan-receipt.json"),JSON.stringify({scope:"Public BBBC013 DRAQ workflow wiring; initial manual masks intentionally empty; no quantitative or human-usability claim",planVersion:"2.1.0",planningBackgroundAnswer:"unknown",actualChannelConfirmationSeparate:true,actualMetricSelectionRequired:true,modeChangeAndSubsequentMetricChangeRequireNewAcknowledgement:true,actualBackgroundRequiredForIntensity:true,changedChildUnreviewed:true,latestResolution:latest.config.plan_resolution,pageErrors:errors},null,2));
});
