import {test,expect,type Page,type APIResponse} from "@playwright/test";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {createRegionWorkspace,workspaceTestRuntime} from "./workspace-session";
import {verifyVectorDownloads} from "./figure-download";
const {api,python,dataDir}=workspaceTestRuntime();
async function json(response:Pick<APIResponse,"ok"|"json">){expect(response.ok()).toBeTruthy();return response.json();}
async function waitJob(page:Page,id:string){await expect.poll(async()=>{const job=await json(await page.request.get(`${api}/v1/jobs/${id}`));if(["failed","cancelled"].includes(job.state))throw Error(`Job failed: ${job.error}`);return job.state;},{timeout:240000,intervals:[500,1000]}).toBe("succeeded");}
test("common statistics browser methods retain independent units and vector exports",async({page})=>{
 test.setTimeout(600000);if(!dataDir)throw Error("Isolated data directory required");
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
 const title="Common statistics known pixels";const workspace=await createRegionWorkspace(page,title);const fixture=fs.mkdtempSync(path.join(dataDir,"common-statistics-ui-"));
 execFileSync(python,["-B","-c","import sys,numpy as np,tifffile;from pathlib import Path;p=Path(sys.argv[1]);m=np.zeros((64,64),dtype=np.uint32);m[24:40,24:40]=1;tifffile.imwrite(p/'labels.tif',m);values=[40,50,65,55,75,95,72,88,110];[(lambda a,i:tifffile.imwrite(p/f'{i}.tif',a))(np.where(m,values[i],10).astype(np.uint16),i) for i in range(9)]",fixture]);
 const headers={Origin:new URL(page.url()).origin,"X-Cytellect-Request":"1"};const fields:{id:string}[]=[];
 for(let i=0;i<9;i++)fields.push(await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-fields`,{headers,multipart:{specification:JSON.stringify({version:"1.0.0",channels:[{channel_id:"signal",label:"Known signal",stain:null,identity_confirmed:true,acquisition_saturation_value:null,acquisition_saturation_confirmed:false}],metadata:{condition:["Control","Treatment","High"][Math.floor(i/3)],sample:`sample-${i}`,experimental_unit:`unit-${i}`,acquisition_date:"fixture-batch",pair:`pair-${i%3}`,repeat_length:null},calibration:null}),ch0:{name:`${i}.tif`,mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,`${i}.tif`))},labels:{name:"labels.tif",mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,"labels.tif"))}}})));
 const initial=await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-analyses`,{headers,data:{recipe:{id:"region-2d",version:"1.0.0",region_set_id:"regions",label:"測定領域",source:"imported",defining_channel_id:null},field_ids:fields.map(field=>field.id),backgrounds:Object.fromEntries(fields.map(field=>[field.id,{signal:{polygon:[[0,0],[15,0],[15,15],[0,15]],confirmed:true}}])),exclusions:[]}}));await waitJob(page,initial.job_id);
 await page.getByRole("button",{name:"← 作業一覧",exact:true}).click();await page.getByRole("button",{name:new RegExp(title)}).click();
 await page.getByLabel("領域、チャンネルごとの背景、失敗・除外理由を確認しました。",{exact:true}).check();await page.getByRole("button",{name:"品質確認を完了",exact:true}).click();await expect(page.getByRole("button",{name:"品質確認を完了",exact:true})).toBeDisabled();await page.getByRole("button",{name:/03 統計解析/}).click();
 await page.getByLabel("比較する測定値",{exact:true}).selectOption("signal-mean_corrected");await page.getByLabel("実験デザイン",{exact:true}).selectOption("independent");await page.getByLabel("独立実験単位の定義",{exact:true}).fill("Independent synthetic numerical fixture units");
 for(const condition of ["Control","Treatment","High"])await page.getByLabel(condition,{exact:true}).check();await page.getByLabel("対照群",{exact:true}).selectOption("Control");
 async function confirmations(){await page.getByLabel("独立性と、必要な対応関係を実験記録で確認しました。",{exact:true}).check();await page.getByLabel("撮影・標識・背景と非飽和の信号を比較できると確認しました。",{exact:true}).check();await page.getByLabel("除外・欠測と比較対象を確認しました。",{exact:true}).check();}
 await confirmations();await page.getByText("検定方法と図の設定",{exact:true}).click();
 await page.getByLabel("検定方式",{exact:true}).selectOption("rank");await page.getByLabel("比較図の種類",{exact:true}).selectOption("violin");
 async function runCommon(button:string){const pending=page.waitForResponse(response=>response.url().endsWith("/common-statistics")&&response.request().method()==="POST");await page.getByRole("button",{name:button,exact:true}).click();const created=await json(await pending);await waitJob(page,created.job_id);const result=await json(await page.request.get(`${api}/v1/jobs/${created.job_id}/common-statistics`));for(const file of result.figure.source_files)expect((await page.request.get(`${api}/v1/jobs/${created.job_id}/files/${file}`)).ok(),file).toBeTruthy();return {created,result};}
 const rank=await runCommon("比較と図を作成");expect(rank.result.spec).toMatchObject({version:"2.0.0",test:"mann-whitney-u",omnibus:"kruskal-wallis",plot:{kind:"violin"}});expect(rank.result.counts.map((row:{experimental_units:number})=>row.experimental_units)).toEqual([3,3,3]);expect(rank.result.comparisons).toHaveLength(2);expect(rank.result.comparisons.every((row:{estimate:null;ci_low:null})=>row.estimate===null&&row.ci_low===null)).toBe(true);await expect(page.getByLabel("全体検定の結果",{exact:true})).toContainText("Kruskal");await verifyVectorDownloads(page,{width:183/25.4,height:3,labels:[]});
 await page.getByLabel("検定方式",{exact:true}).selectOption("parametric");await page.getByLabel("比較図の種類",{exact:true}).selectOption("histogram");await page.getByLabel("比較図のビン数",{exact:true}).fill("12");const anova=await runCommon("比較と図を作成");expect(anova.result.spec).toMatchObject({test:"welch-t",omnibus:"welch-anova",plot:{kind:"histogram",histogram_bins:12}});expect(anova.result.comparisons[0].estimate).toBeCloseTo(-23.3333333333,8);
 await page.getByLabel("比較図の種類",{exact:true}).selectOption("box");const box=await runCommon("比較と図を作成");expect(box.result.spec.plot.kind).toBe("box");
 await page.getByLabel("High",{exact:true}).uncheck();await page.getByLabel("実験デザイン",{exact:true}).selectOption("paired");await page.getByLabel("対応の根拠",{exact:true}).fill("Matched synthetic numerical fixture identifiers");await confirmations();await page.getByLabel("検定方式",{exact:true}).selectOption("rank");const paired=await runCommon("比較と図を作成");expect(paired.result.spec).toMatchObject({test:"wilcoxon",omnibus:null,plot:{kind:"paired"}});expect(paired.result.pair_ledger).toHaveLength(3);
 await page.getByRole("button",{name:"相関解析",exact:true}).click();const association=page.getByRole("region",{name:"相関解析",exact:true});
 await association.getByLabel("相関の横軸",{exact:true}).selectOption("signal-mean_corrected");await association.getByLabel("相関の縦軸",{exact:true}).selectOption("signal-integrated_corrected");await association.getByLabel("相関の条件 Control",{exact:true}).check();await association.getByLabel("相関の独立実験単位の定義",{exact:true}).fill("Independent synthetic fixture units");
 for(const label of ["相関に用いる実験単位の独立性を確認しました。","両軸の撮影条件・領域定義と測定尺度を確認しました。","両軸の画素サイズと空間サンプリングを確認しました。","両軸の除外・欠測と対応する実験単位を確認しました。"])await association.getByLabel(label,{exact:true}).check();
 const associationChecks=["相関に用いる実験単位の独立性を確認しました。","両軸の撮影条件・領域定義と測定尺度を確認しました。","両軸の画素サイズと空間サンプリングを確認しました。","両軸の除外・欠測と対応する実験単位を確認しました。"];
 const poolingLabel="条件を統合する根拠を確認し、群・撮影バッチの差が相関に与える影響を検討しました。";
 await association.getByLabel("相関の解析範囲",{exact:true}).selectOption("pooled");await expect(association.getByRole("button",{name:"相関と図を作成",exact:true})).toBeDisabled();await association.getByLabel(poolingLabel,{exact:true}).check();await expect(association.getByRole("button",{name:"相関と図を作成",exact:true})).toBeEnabled();
 await association.getByLabel("相関の条件 Treatment",{exact:true}).check();for(const label of [...associationChecks,poolingLabel])await expect(association.getByLabel(label,{exact:true})).not.toBeChecked();await expect(association.getByRole("button",{name:"相関と図を作成",exact:true})).toBeDisabled();await expect(association.getByLabel("相関の独立実験単位の定義",{exact:true})).toHaveValue("Independent synthetic fixture units");
 await association.getByLabel("相関の条件 Treatment",{exact:true}).uncheck();for(const label of [...associationChecks,poolingLabel])await association.getByLabel(label,{exact:true}).check();
 await association.getByLabel("相関の縦軸",{exact:true}).selectOption("signal-integrated");for(const label of [...associationChecks.slice(1),poolingLabel])await expect(association.getByLabel(label,{exact:true})).not.toBeChecked();await expect(association.getByLabel(associationChecks[0],{exact:true})).toBeChecked();await expect(association.getByRole("button",{name:"相関と図を作成",exact:true})).toBeDisabled();
 await association.getByLabel("相関の縦軸",{exact:true}).selectOption("signal-integrated_corrected");await association.getByLabel("相関の解析範囲",{exact:true}).selectOption("per-condition");for(const label of associationChecks)await association.getByLabel(label,{exact:true}).check();
 await association.getByText("相関図の設定",{exact:true}).click();await association.getByText("軸ラベル・寸法・表示順",{exact:true}).click();await association.getByLabel("相関図の横軸ラベル",{exact:true}).fill("Mean signal");await association.getByLabel("相関図の縦軸ラベル",{exact:true}).fill("Integrated signal");
 const pearson=await runCommon("相関と図を作成");expect(pearson.result.spec).toMatchObject({method:"pearson",scope:"per-condition"});expect(pearson.result.associations[0]).toMatchObject({n_units:3,coefficient:1});await expect(association.getByAltText("独立実験単位の散布図",{exact:true})).toBeVisible();await verifyVectorDownloads(page,{width:183/25.4,height:3,labels:["Mean signal","Integrated signal"]});
 await expect(association.getByRole("button",{name:"横軸 · 図の元データ ↓",exact:true})).toHaveCount(0);await association.getByText("元データ・集計表",{exact:true}).click();const sourcePending=page.waitForEvent("download");await association.getByRole("button",{name:"横軸 · 図の元データ ↓",exact:true}).click();const sourceDownload=await sourcePending;expect(await sourceDownload.failure()).toBeNull();expect(sourceDownload.suggestedFilename()).toBe("x-plot-data.csv");await association.getByText("元データ・集計表",{exact:true}).click();
 await expect(association.getByLabel("保存済みの相関横軸",{exact:true})).toContainText("Known signal · 平均（背景補正）");await expect(association.getByLabel("保存済みの相関縦軸",{exact:true})).toContainText("Known signal · 積算（背景補正）");
 await association.getByLabel("相関の縦軸",{exact:true}).selectOption("signal-mean");await expect(association.getByLabel("保存済みの相関縦軸",{exact:true})).toContainText("Known signal · 積算（背景補正）");await association.getByLabel("相関の縦軸",{exact:true}).selectOption("signal-integrated_corrected");for(const label of associationChecks)await association.getByLabel(label,{exact:true}).check();
 await association.getByLabel("相関係数",{exact:true}).selectOption("spearman");const spearman=await runCommon("相関と図を作成");expect(spearman.result.spec.method).toBe("spearman");expect(spearman.result.associations[0].coefficient).toBeCloseTo(1,12);expect(spearman.result.associations[0].p_value).toBeCloseTo(1/3,12);
 const saved=association.locator('[aria-label="保存済みの相関解析"]');await expect(saved.getByRole("heading",{name:"Spearmanの順位相関",exact:true})).toBeVisible();
 const scatter=saved.getByAltText("独立実験単位の散布図",{exact:true});await expect(scatter).toBeVisible();await expect.poll(()=>scatter.evaluate(image=>(image as HTMLImageElement).complete&&(image as HTMLImageElement).naturalWidth>0)).toBe(true);
 const savedRow=saved.getByRole("row").filter({has:page.getByRole("cell",{name:"Control",exact:true})});await expect(savedRow.getByRole("cell").nth(1)).toHaveText("3");await expect(savedRow.getByRole("cell").nth(3)).toHaveText("0.333");await expect(savedRow.getByRole("cell").nth(4)).toHaveText("0.333");
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
 const evidence=process.env.CYTELLECT_SCREENSHOT_DIR;if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.screenshot({path:path.join(evidence,"common-statistics-mobile.png"),fullPage:true});fs.writeFileSync(path.join(evidence,"common-statistics-receipt.json"),JSON.stringify({source:"Synthetic known-pixel software test; no biological inference claim",revision:initial.revision_id,jobs:[rank,anova,box,paired,pearson,spearman].map(item=>({id:item.created.job_id,sourceFingerprint:item.result.source_fingerprint,spec:item.result.spec})),pageErrors:errors},null,2));}
});
