import {test,expect,type Page,type APIResponse} from "@playwright/test";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {expectGfpPreview} from "./image-preview";
import {workspaceTestRuntime,createRegionWorkspace} from "./workspace-session";

const root=path.resolve(__dirname,"../../..");
const {api,python,dataDir}=workspaceTestRuntime();
const evidence=process.env.CYTELLECT_SCREENSHOT_DIR;
async function json(response:Pick<APIResponse,"ok"|"json">){expect(response.ok()).toBeTruthy();return response.json();}
async function mutation(page:Page,suffix:string,action:()=>Promise<void>){const response=page.waitForResponse(r=>r.url().includes(suffix)&&r.request().method()==="POST");await action();return json(await response);}
async function waitJob(page:Page,id:string){await expect.poll(async()=>{const job=await json(await page.request.get(`${api}/v1/jobs/${id}`));if(["failed","cancelled"].includes(job.state))throw Error(`Job failed: ${job.error}`);return job.state;},{timeout:240000,intervals:[500,1000]}).toBe("succeeded");}
const create=createRegionWorkspace;
async function background(page:Page){await page.getByRole("button",{name:"背景",exact:true}).click();const details=page.locator("details").filter({has:page.locator(":scope > summary",{hasText:"座標から多角形を指定"})});if(!await details.evaluate(el=>(el as HTMLDetailsElement).open))await details.locator(":scope > summary").click();await page.getByLabel("頂点（x,y を空白または改行で区切る）").fill("0,0 15,0 15,15 0,15");await page.getByRole("button",{name:"座標を反映",exact:true}).click();await page.getByRole("button",{name:/^背景を確定/}).click();}
async function shot(page:Page,name:string){if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.screenshot({path:path.join(evidence,name),fullPage:true});}}
async function review(page:Page){await page.getByLabel("領域、チャンネルごとの背景、失敗・除外理由を確認しました。",{exact:true}).check();await mutation(page,"/review",()=>page.getByRole("button",{name:"品質確認を完了",exact:true}).click());await expect(page.getByRole("button",{name:"品質確認を完了",exact:true})).toBeDisabled();}

for(const channelCount of [1,2])test(`confirmed ${channelCount}-channel nuclear detection preserves corrected regions during batch and requires explicit re-detection`,async({page})=>{
 test.setTimeout(420000);const publicFixture=process.env.CYTELLECT_TEST_REGION_FIXTURES;
 const fixture=publicFixture?{image:path.join(publicFixture,"a9-dna.tif"),label:"核染色",stain:"",second:path.join(publicFixture,"a9-actin.tif"),secondLabel:"Actin",dataset:"BBBC007 a9"}:{image:path.join(root,"fixtures/public/bbbc013/A01-dapi.tif"),label:"DRAQ",stain:"DRAQ",second:path.join(root,"fixtures/public/bbbc013/A01-gfp.tif"),secondLabel:"FKHR-EGFP",dataset:"BBBC013 A01"};
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));await create(page,"Public nuclear stain workflow");
 async function upload(first:boolean){if(!first)await page.getByText("＋ 画像を登録",{exact:true}).click();if(first){await page.getByLabel("チャンネル 1 の表示名",{exact:true}).fill(fixture.label);await page.getByLabel("チャンネル 1 の染色",{exact:true}).fill(fixture.stain);}await page.getByLabel("チャンネル 1 の画像",{exact:true}).setInputFiles(fixture.image);await page.getByLabel("チャンネル 1 の画像と表示名の対応を確認しました。",{exact:true}).check();if(channelCount===2){if(first){await page.getByRole("button",{name:"チャンネルを追加",exact:true}).click();await page.getByLabel("チャンネル 2 の表示名",{exact:true}).fill(fixture.secondLabel);}await page.getByLabel("チャンネル 2 の画像",{exact:true}).setInputFiles(fixture.second);await page.getByLabel("チャンネル 2 の画像と表示名の対応を確認しました。",{exact:true}).check();}return mutation(page,"/region-fields",()=>page.getByRole("button",{name:"この視野を登録",exact:true}).click());}
 async function backgrounds(){await page.getByRole("button",{name:fixture.label,exact:true}).click();await background(page);if(channelCount===2){await page.getByRole("button",{name:fixture.secondLabel,exact:true}).click();await background(page);}}
 const first=await upload(true);await page.getByLabel("領域の作り方",{exact:true}).selectOption("stardist_nuclear");await backgrounds();await expect(page.getByRole("button",{name:"この視野で検出を試す",exact:true})).toBeDisabled();await page.getByLabel("このチャンネルが核を染めた画像であることを確認しました。",{exact:true}).check();
 const submitted=page.waitForRequest(request=>request.url().endsWith("/region-analyses")&&request.method()==="POST");const detected=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"この視野で検出を試す",exact:true}).click());expect((await submitted).postDataJSON().recipe).toMatchObject({version:"1.1.0",source:"stardist_nuclear",defining_channel_id:"channel-1",nuclear_stain_confirmed:true});await waitJob(page,detected.job_id);
 const original=await json(await page.request.get(`${api}/v1/revisions/${detected.revision_id}/region-masks?field_id=${first.id}`));expect(original.metadata.source).toBe("stardist_nuclear");expect(original.regions.length).toBeGreaterThan(10);await expect(page.getByRole("table").filter({has:page.getByRole("columnheader",{name:"領域ID",exact:true})}).locator("tbody tr")).toHaveCount(original.regions.length);await expectGfpPreview(page);
 const deletedId=original.regions[0].id;await page.getByLabel("選択した領域ID",{exact:true}).fill(String(deletedId));await page.getByRole("button",{name:"削除",exact:true}).click();const edited=await mutation(page,"/region-edits",()=>page.getByRole("button",{name:"選択した領域を削除・再測定",exact:true}).click());await waitJob(page,edited.job_id);await expect(page.getByRole("table").filter({has:page.getByRole("columnheader",{name:"領域ID",exact:true})}).locator("tbody tr")).toHaveCount(original.regions.length-1);const corrected=await json(await page.request.get(`${api}/v1/revisions/${edited.revision_id}/region-masks?field_id=${first.id}`));
 const second=await upload(false);await backgrounds();const batchRequest=page.waitForRequest(request=>request.url().endsWith("/region-analyses")&&request.method()==="POST");const batch=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"領域を保持して全視野を測定",exact:true}).click());expect((await batchRequest).postDataJSON().reuse_revision).toBe(edited.revision_id);await waitJob(page,batch.job_id);expect(await json(await page.request.get(`${api}/v1/revisions/${batch.revision_id}/region-masks?field_id=${first.id}`))).toEqual(corrected);expect((await json(await page.request.get(`${api}/v1/revisions/${batch.revision_id}/region-masks?field_id=${second.id}`))).regions).toHaveLength(original.regions.length);
 await page.getByText("検出の詳細設定",{exact:true}).click();await page.getByLabel("確率閾値",{exact:true}).fill("0.6");await expect(page.getByRole("button",{name:"背景・除外を反映して再測定",exact:true})).toBeDisabled();await page.getByRole("button",{name:"新しい条件で全視野を再作成",exact:true}).click();await expect(page.getByRole("button",{name:"修正領域を引き継がず再作成",exact:true})).toBeVisible();await expect(page.getByText(/2 視野の領域を作り直します/)).toBeVisible();await page.getByRole("button",{name:"戻る",exact:true}).click();await page.getByRole("button",{name:"保存済みの条件に戻す",exact:true}).click();
 // Reverting a setting leaves an explicit remeasurement draft. Save before the subsequent quality review.
 if(await page.getByRole("button",{name:"背景・除外を反映して再測定",exact:true}).isEnabled()){const restored=await mutation(page,"/region-reconfigure",()=>page.getByRole("button",{name:"背景・除外を反映して再測定",exact:true}).click());await waitJob(page,restored.job_id);}
 await page.getByRole("button",{name:"この視野を再検出",exact:true}).click();await expect(page.getByText(/1 視野の領域を作り直します/)).toBeVisible();await page.getByRole("button",{name:"戻る",exact:true}).click();await review(page);
 await shot(page,`nuclear-region-${channelCount}ch-desktop.png`);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,`nuclear-region-${channelCount}ch-mobile.png`);await page.setViewportSize({width:1440,height:1000});
 await page.getByRole("button",{name:/02 分布と図/}).click();const figure=await mutation(page,"/descriptive",()=>page.getByRole("button",{name:"分布図を作成",exact:true}).click());await waitJob(page,figure.job_id);await expect(page.getByAltText("領域の測定値と視野内中央値の分布図",{exact:true})).toBeVisible();expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,`nuclear-region-${channelCount}ch-receipt.json`),JSON.stringify({dataset:fixture.dataset,stain:fixture.stain||null,channels:channelCount,nuclearRoleExplicit:true,originalRegions:original.regions.length,correctedRegions:corrected.regions.length,correctedMaskRetainedExactly:true,changedRecipeConfirmation:true,singleFieldRedetectionConfirmation:true,note:"Public image UI/engine verification; duplicate field tests mask retention, not biological replication or segmentation accuracy.",pageErrors:errors},null,2));
});

test("declared independent and paired region comparisons retain metadata, source counts and manifest downloads",async({page})=>{
 test.setTimeout(240000);if(!dataDir)throw Error("Isolated data directory required");const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const title="Synthetic design and source linkage";const workspace=await create(page,title);const fixture=fs.mkdtempSync(path.join(dataDir,"comparison-ui-"));
 execFileSync(python,["-c","import sys,numpy as np,tifffile;from pathlib import Path;p=Path(sys.argv[1]);m=np.zeros((64,64),dtype=np.uint32);m[24:40,24:40]=1;tifffile.imwrite(p/'labels.tif',m);values=[40,50,65,55,75,95];[(lambda a,i:tifffile.imwrite(p/f'{i}.tif',a))(np.where(m,values[i],10).astype(np.uint16),i) for i in range(6)]",fixture]);
 const origin=new URL(page.url()).origin;const headers={Origin:origin,"X-Cytellect-Request":"1"};const fields=[];
 for(let i=0;i<6;i++){fields.push(await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-fields`,{headers,multipart:{specification:JSON.stringify({version:"1.0.0",channels:[{channel_id:"signal",label:"検証信号",stain:null,identity_confirmed:true,acquisition_saturation_value:null,acquisition_saturation_confirmed:false}],metadata:{condition:null,sample:null,experimental_unit:null,acquisition_date:null,pair:null,repeat_length:null},calibration:null}),ch0:{name:`${i}.tif`,mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,`${i}.tif`))},labels:{name:"labels.tif",mimeType:"image/tiff",buffer:fs.readFileSync(path.join(fixture,"labels.tif"))}}})));}
 const initial=await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-analyses`,{headers,data:{recipe:{id:"region-2d",version:"1.0.0",region_set_id:"regions",label:"測定領域",source:"imported",defining_channel_id:null},field_ids:fields.map(field=>field.id),backgrounds:Object.fromEntries(fields.map(field=>[field.id,{signal:{polygon:[[0,0],[15,0],[15,15],[0,15]],confirmed:true}}])),exclusions:[]}}));await waitJob(page,initial.job_id);
 await page.getByRole("button",{name:"← 作業一覧",exact:true}).click();await page.getByRole("button",{name:new RegExp(title)}).click();await page.getByRole("button",{name:/03 実験単位で比較/}).click();await expect(page.getByRole("button",{name:"比較と図を作成",exact:true})).toBeDisabled();await expect(page.getByLabel("実験デザイン",{exact:true})).toHaveValue("");
 for(let i=0;i<6;i++){for(const [label,value] of [["条件",i<3?"Control":"Treatment"],["試料",`sample-${i+1}`],["独立実験単位",`unit-${i+1}`],["撮影日／バッチ","synthetic-batch"],["対応ペア",`pair-${i%3+1}`]])await page.getByLabel(`視野 ${i+1} の${label}`,{exact:true}).fill(value);}
 const metadata=await mutation(page,"/region-metadata",()=>page.getByRole("button",{name:"実験情報を新しい解析版に保存",exact:true}).click());await waitJob(page,metadata.job_id);await expect(page.getByLabel("視野 1 の条件",{exact:true})).toHaveValue("Control");await expect(page.getByRole("button",{name:"比較と図を作成",exact:true})).toBeDisabled();await page.getByRole("region",{name:"比較の前に確認すること",exact:true}).getByRole("button",{name:"画像と品質確認へ",exact:true}).click();await review(page);await page.getByRole("button",{name:/03 実験単位で比較/}).click();
 const originals=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}/region-fields`));expect(originals.every((field:{metadata:{condition:null|string}})=>field.metadata.condition===null)).toBe(true);const versions=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}/revisions`));const saved=versions.find((revision:{id:string})=>revision.id===metadata.revision_id);expect(saved.config.field_snapshot[fields[0].id].metadata.condition).toBe("Control");
 await page.getByLabel("比較する測定値",{exact:true}).selectOption("signal-mean_corrected");await page.getByLabel("実験デザイン",{exact:true}).selectOption("independent");await page.getByLabel("独立実験単位の定義",{exact:true}).fill("Independent synthetic fixture units for software verification");await page.getByLabel("Control",{exact:true}).check();await page.getByLabel("Treatment",{exact:true}).check();await page.getByLabel("対照群",{exact:true}).selectOption("Control");await page.getByLabel("独立性と、必要な対応関係を実験記録で確認しました。",{exact:true}).check();await page.getByLabel("撮影・標識・背景と非飽和の信号を比較できると確認しました。",{exact:true}).check();await page.getByLabel("除外・欠測と比較対象を確認しました。",{exact:true}).check();
 const compared=await mutation(page,"/region-comparisons",()=>page.getByRole("button",{name:"比較と図を作成",exact:true}).click());await waitJob(page,compared.job_id);const result=await json(await page.request.get(`${api}/v1/jobs/${compared.job_id}/region-comparison`));expect(result.spec.design.kind).toBe("independent");for(const name of result.figure.source_files){expect((await page.request.get(`${api}/v1/jobs/${compared.job_id}/files/${name}`)).ok(),name).toBeTruthy();}expect(result.counts.map((row:{experimental_units:number})=>row.experimental_units)).toEqual([3,3]);expect(result.comparisons[0].estimate).toBeCloseTo(-23.3333333333,8);await expect(page.getByLabel("保存済みの比較指標",{exact:true})).toContainText("検証信号");
 const image=page.getByAltText("実験単位の集計値と群間比較の図",{exact:true});await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0)).toBe(true);
 for(const name of ["比較結果 ↓","実験単位集計 ↓","SVG ↓"]){const pending=page.waitForEvent("download");await page.getByRole("button",{name,exact:true}).click();const file=await pending;expect(await file.failure()).toBeNull();if(evidence)await file.saveAs(path.join(evidence,`region-${file.suggestedFilename()}`));}
 await page.getByLabel("実験デザイン",{exact:true}).selectOption("paired");await page.getByLabel("対応の根拠",{exact:true}).fill("Declared synthetic paired fixture identity");await page.getByLabel("独立性と、必要な対応関係を実験記録で確認しました。",{exact:true}).check();await page.getByText("集計方法と図の設定",{exact:true}).click();await expect(page.getByText("対応ありでは、宣言したペアを線で結びます。",{exact:true})).toBeVisible();
 let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;});await page.route("**/region-comparisons",async route=>{if(route.request().method()==="POST")await gate;await route.continue();});const pairedPromise=mutation(page,"/region-comparisons",()=>page.getByRole("button",{name:"比較と図を作成",exact:true}).click());await expect(page.getByText("比較と図の生成を受け付けています。",{exact:true})).toBeVisible();await expect(image).toHaveCount(0);await expect(page.getByRole("button",{name:"SVG ↓",exact:true})).toHaveCount(0);release();const paired=await pairedPromise;await page.unroute("**/region-comparisons");await waitJob(page,paired.job_id);const pairedResult=await json(await page.request.get(`${api}/v1/jobs/${paired.job_id}/region-comparison`));expect(pairedResult.spec.plot.kind).toBe("paired");expect(pairedResult.pair_ledger).toHaveLength(3);await expect(image).toBeVisible();await expect.poll(()=>image.evaluate(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0)).toBe(true);
 await shot(page,"region-comparison-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"region-comparison-mobile.png");await page.setViewportSize({width:1440,height:1000});await page.getByRole("button",{name:"この解析版の画像を確認",exact:true}).first().click();await expect(page.getByRole("heading",{name:"測定値と品質確認",exact:true})).toBeVisible();await page.getByRole("button",{name:/04 保存と履歴/}).click();await expect(page.getByLabel("原画像もZIPへ含める",{exact:true})).not.toBeChecked();const exported=await mutation(page,"/export?",()=>page.getByRole("button",{name:"解析パッケージを生成",exact:true}).click());await waitJob(page,exported.job_id);const pendingZip=page.waitForEvent("download");await page.getByRole("button",{name:"ZIPを保存 ↓",exact:true}).click();const zip=await pendingZip;expect(await zip.failure()).toBeNull();const zipPath=path.join(evidence||fixture,"region-comparison-bundle.zip");await zip.saveAs(zipPath);
 const verified=JSON.parse(execFileSync(python,["-c",`import sys,json,zipfile,hashlib
from pathlib import Path
from cytellect_analysis.region_exports import replay_region_bundle
from cytellect_worker.provenance import software_identity
import cytellect_analysis,cytellect_api,cytellect_worker
archive=Path(sys.argv[1]);bundle=archive.parent/'region-comparison-unpacked';target=archive.parent/'region-comparison-replayed'
assert not bundle.exists() and not target.exists()
with zipfile.ZipFile(archive) as z:
 m=json.loads(z.read('manifest.json'));assert m['raw_included'] is False
 assert not any(p.startswith('raw/') for p in z.namelist())
 assert all(not Path(p).is_absolute() and '..' not in Path(p).parts for p in z.namelist())
 assert all(hashlib.sha256(z.read(p)).hexdigest()==h for p,h in m['files'].items())
 results=[json.loads(z.read(p)) for p in z.namelist() if p.startswith('statistics/') and p.endswith('/result.json')]
 assert len(results)==2 and all(r['analysis_kind']=='region-comparison' for r in results)
 provenance=json.loads(z.read('provenance.json'));assert provenance['software']['source_sha256']==software_identity()['source_sha256']
 z.extractall(bundle)
if sys.argv[3]=='1':
 app=Path(sys.executable).resolve().parents[2]
 assert all(Path(module.__file__).resolve().is_relative_to(app) for module in (cytellect_analysis,cytellect_api,cytellect_worker))
replayed=replay_region_bundle(bundle,Path(sys.argv[2]),target)
assert replayed['matched_saved_measurements'] and replayed['matched_saved_comparisons']
print(json.dumps({'raw_included':False,'verified_files':len(m['files']),'comparisons':len(results),'matched_saved_measurements':True,'matched_saved_comparisons':True,'installed_imports_verified':sys.argv[3]=='1','source_sha256':provenance['software']['source_sha256'],'git_commit':provenance['software']['git_commit']}))`,zipPath,path.join(dataDir,"workspaces",workspace.id,"fields"),process.env.CYTELLECT_TEST_LOCAL||"0"],{encoding:"utf8"}));expect(verified.matched_saved_comparisons).toBe(true);expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"region-comparison-receipt.json"),JSON.stringify({source:"Synthetic known-pixel numerical fixtures; no public-image biological replication or efficacy claim",immutableSourceMetadataPreserved:true,snapshotMetadataEdited:true,independentCounts:result.counts,estimate:result.comparisons[0].estimate,pairedCounts:pairedResult.counts,pairedLedger:pairedResult.pair_ledger,newPendingHidesOldFigure:true,manifestDownloads:true,sourceImageLink:true,exportAndReplay:verified,pageErrors:errors},null,2));
});
