import {test,expect,type Page} from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import {createRegionWorkspace,workspaceTestRuntime} from "./workspace-session";
const {api}=workspaceTestRuntime();const root=path.resolve(__dirname,"../../..");const evidence=process.env.CYTELLECT_SCREENSHOT_DIR;
const raw=path.join(root,"fixtures/public/bbbc013/A01-dapi.tif");
async function json(response:{ok():boolean;json():Promise<unknown>}){expect(response.ok()).toBe(true);return response.json() as Promise<Record<string,unknown>>;}
async function mutation(page:Page,suffix:string,action:()=>Promise<void>){const pending=page.waitForResponse(response=>response.url().includes(suffix)&&response.request().method()==="POST");await action();return json(await pending);}
async function job(page:Page,id:unknown){await expect.poll(async()=>{const value=await json(await page.request.get(`${api}/v1/jobs/${id}`));if(value.state==="failed")throw Error(`Job failed: ${value.error}`);return value.state;},{timeout:240000}).toBe("succeeded");}
async function background(page:Page){await page.getByRole("button",{name:"背景",exact:true}).click();await page.getByText("座標から多角形を指定",{exact:true}).click();await page.getByLabel("頂点（x,y を空白または改行で区切る）").fill("0,0 15,0 15,15 0,15");await page.getByRole("button",{name:"座標を反映",exact:true}).click();await page.getByRole("button",{name:/^背景を確定/}).click();}
async function shot(page:Page,name:string){if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.screenshot({path:path.join(evidence,name),fullPage:true});}}
const plan={format:"cytellect-analysis-plan",version:"2.0.0",answers:{measurement:"mean",region:"custom",definition:"manual",signal:"other",input:"grayscale-2d",nuclear_stain:"unknown",background:"yes",acquisition:"matched",comparison:"independent",allocation:"biological",gating:"none"}};

test("planning intent crosses React memory but actual image confirmations and metric choices remain explicit",async({page})=>{
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));await createRegionWorkspace(page,"Planning session bootstrap");await page.getByRole("button",{name:"← 作業一覧",exact:true}).click();await page.getByRole("link",{name:"計画ガイドを開く →",exact:true}).click();
 await page.getByLabel("測りたい量",{exact:true}).selectOption("mean");await page.getByLabel("測定する領域",{exact:true}).selectOption("custom");await page.getByLabel("領域の決め方",{exact:true}).selectOption("manual");await page.getByLabel("測定する蛍光チャンネル",{exact:true}).selectOption("other");await page.getByLabel("測定に使う画像",{exact:true}).selectOption("grayscale-2d");await page.getByLabel("画像内の背景領域",{exact:true}).selectOption("yes");await page.getByRole("radio",{name:"手動領域の面積・輝度",exact:true}).check();await page.getByRole("button",{name:/この計画で作業を作成/}).click();
 await expect(page.getByLabel("採用する計画候補",{exact:true})).toHaveValue("regions-manual");await expect(page.getByLabel("解析の種類",{exact:true})).toBeDisabled();await page.getByLabel("作業名",{exact:true}).fill("Plan handoff public image check");const workspace=await mutation(page,"/v1/workspaces",()=>page.getByRole("button",{name:"作業を作成 ＋",exact:true}).click());expect(workspace.analysis_plan).toMatchObject({selected_candidate_id:"regions-manual",scope:"planning-intent-only"});
 await expect(page.getByLabel("計画に対応する実チャンネルと指標",{exact:true})).toHaveValue("");await page.getByLabel("チャンネル 1 の表示名",{exact:true}).fill("DRAQ");await page.getByLabel("チャンネル 1 の染色",{exact:true}).fill("DRAQ");await page.getByLabel("チャンネル 1 の画像",{exact:true}).setInputFiles(raw);await expect(page.getByLabel("チャンネル 1 の画像と表示名の対応を確認しました。",{exact:true})).not.toBeChecked();await page.getByLabel("チャンネル 1 の画像と表示名の対応を確認しました。",{exact:true}).check();await mutation(page,"/region-fields",()=>page.getByRole("button",{name:"この視野を登録",exact:true}).click());
 await expect(page.getByRole("button",{name:"この視野で始める",exact:true})).toBeDisabled();await background(page);await expect(page.getByRole("button",{name:"この視野で始める",exact:true})).toBeDisabled();await page.getByLabel("計画に対応する実チャンネルと指標",{exact:true}).selectOption("channel-1-mean_corrected");const analyzed=await mutation(page,"/region-analyses",()=>page.getByRole("button",{name:"この視野で始める",exact:true}).click());await job(page,analyzed.job_id);
 const revisions=await (await page.request.get(`${api}/v1/workspaces/${workspace.id}/revisions`)).json();expect(revisions.find((revision:{id:string})=>revision.id===analyzed.revision_id).config.analysis_plan.resolved).toMatchObject({metric:"mean_corrected",channel:{channel_id:"channel-1",label:"DRAQ"}});
 await page.getByRole("button",{name:"追加",exact:true}).click();const coordinates=page.getByLabel("頂点（x,y を空白または改行で区切る）");if(!await coordinates.isVisible())await page.getByText("座標から多角形を指定",{exact:true}).click();await coordinates.fill("30,30 60,30 60,60 30,60");await page.getByRole("button",{name:"座標を反映",exact:true}).click();const edited=await mutation(page,"/region-edits",()=>page.getByRole("button",{name:/領域を保存・再測定/}).click());await job(page,edited.job_id);await page.getByLabel("領域、チャンネルごとの背景、失敗・除外理由を確認しました。",{exact:true}).check();await mutation(page,"/review",()=>page.getByRole("button",{name:"品質確認を完了",exact:true}).click());await page.getByRole("button",{name:/02 分布と図/}).click();await expect(page.getByLabel("表示する測定値",{exact:true})).toHaveValue("channel-1-mean_corrected");const plotted=await mutation(page,"/descriptive",()=>page.getByRole("button",{name:"分布図を作成",exact:true}).click());await job(page,plotted.job_id);const saved=await json(await page.request.get(`${api}/v1/jobs/${plotted.job_id}/result`));expect(saved.spec).toMatchObject({selection:{metric:"mean_corrected",channel_id:"channel-1"}});await expect(page.getByAltText("領域の測定値と視野内中央値の分布図",{exact:true})).toBeVisible();await page.getByRole("button",{name:/03 実験単位で比較/}).click();await expect(page.getByLabel("比較する測定値",{exact:true})).toHaveValue("channel-1-mean_corrected");await expect(page.getByLabel("実験デザイン",{exact:true})).toHaveValue("");await page.getByRole("button",{name:/01 画像と領域/}).click();
 await page.getByLabel("計画に対応する実チャンネルと指標",{exact:true}).selectOption("area_px");await expect(page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true})).not.toBeChecked();await page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true}).check();await page.getByLabel("計画に対応する実チャンネルと指標",{exact:true}).selectOption("channel-1-median");await expect(page.getByLabel("変更した内容を確認し、この条件で進めます。",{exact:true})).not.toBeChecked();await shot(page,"plan-actual-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"plan-actual-mobile.png");expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0]);expect(errors).toEqual([]);
});

test("imported plans are recomputed and rejected old or forged guidance cannot create an adopted workspace",async({page})=>{
 await createRegionWorkspace(page,"Imported plan bootstrap");await page.getByRole("button",{name:"← 作業一覧",exact:true}).click();const input=page.getByLabel("保存した計画JSON",{exact:true});await input.setInputFiles({name:"old-plan.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({...plan,version:"1.0.1"}))});await expect(page.getByRole("alert")).toContainText("以前の計画");await expect(page.getByRole("button",{name:"作業を作成 ＋",exact:true})).toBeDisabled();
 await input.setInputFiles({name:"forged-plan.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify({...plan,guidance:{ready:true}}))});await expect(page.getByRole("alert")).toContainText("対応していない");await input.setInputFiles({name:"current-plan.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(plan))});await expect(page.getByLabel("採用する計画候補",{exact:true})).toHaveValue("");await expect(page.getByRole("button",{name:"作業を作成 ＋",exact:true})).toBeDisabled();await page.getByLabel("採用する計画候補",{exact:true}).selectOption("regions-manual");await page.getByLabel("作業名",{exact:true}).fill("Imported current plan");const workspace=await mutation(page,"/v1/workspaces",()=>page.getByRole("button",{name:"作業を作成 ＋",exact:true}).click());expect(workspace.analysis_plan).toMatchObject({input:plan,selected_candidate_id:"regions-manual"});
});

test("batch mapping rejects missing images and retry recovers an acknowledged-lost upload without duplicate fields",async({page})=>{
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));const workspace=await createRegionWorkspace(page,"Batch registration public pixels");await page.getByText("＋ 複数視野をまとめて登録",{exact:true}).click();const bytes=fs.readFileSync(raw);const first=["field1_DNA.tif","field2_DNA.tif"].map(name=>({name,mimeType:"image/tiff",buffer:bytes}));const second=["field1_other.tif","field2_other.tif"].map(name=>({name,mimeType:"image/tiff",buffer:bytes}));
 await page.getByLabel("一括 チャンネル 1 の表示名",{exact:true}).fill("DRAQ");await page.getByLabel("一括 チャンネル 1 の染色",{exact:true}).fill("DRAQ");await page.getByLabel("一括 チャンネル 1 の画像",{exact:true}).setInputFiles(first);await page.getByLabel("一括 チャンネル 1 の末尾文字",{exact:true}).fill("_DNA");await page.getByRole("button",{name:"一括のチャンネルを追加",exact:true}).click();await page.getByLabel("一括 チャンネル 2 の表示名",{exact:true}).fill("Repeated DRAQ for mapping test");await page.getByLabel("一括 チャンネル 2 の染色",{exact:true}).fill("DRAQ");await page.getByLabel("一括 チャンネル 2 の画像",{exact:true}).setInputFiles(second.slice(0,1));await page.getByLabel("一括 チャンネル 2 の末尾文字",{exact:true}).fill("_other");await expect(page.getByRole("button",{name:/確認した視野を登録/})).toBeDisabled();
 await page.getByLabel("一括 チャンネル 2 の画像",{exact:true}).setInputFiles(second);for(const i of [1,2])await page.getByLabel(`チャンネル ${i} の全画像と表示名の対応を確認しました。`,{exact:true}).check();await page.getByText("共通の実験情報",{exact:true}).click();await page.getByLabel("一括 共通の条件",{exact:true}).fill("Software test only");await page.getByRole("button",{name:"共通情報を全行へ適用",exact:true}).click();await page.getByLabel("全視野の画像対応と実験情報を確認しました。",{exact:true}).check();
 let lost=false;const ids:string[]=[];await page.route("**/region-fields",async route=>{if(route.request().method()!=="POST"){await route.continue();return;}const body=route.request().postData()||"";const match=body.match(/"client_upload_id":"([a-f0-9-]+)"/);if(match)ids.push(match[1]);const response=await route.fetch();if(!lost){lost=true;expect(response.ok()).toBe(true);await route.abort("failed");}else await route.fulfill({response});});
 await page.getByRole("button",{name:/確認した視野を登録/}).click();await expect(page.getByText("登録できなかった視野が残っています。成功した視野は再送しません。",{exact:true})).toBeVisible();await expect.poll(async()=>(await (await page.request.get(`${api}/v1/workspaces/${workspace.id}/region-fields`)).json()).length).toBe(2);await page.getByRole("button",{name:/未登録の視野を再試行/}).click();await expect(page.getByText("全視野を登録しました。代表視野を選び、背景と領域を確認してください。",{exact:true})).toBeVisible();await page.unroute("**/region-fields");expect(ids).toHaveLength(3);expect(ids[2]).toBe(ids[0]);const fields=await (await page.request.get(`${api}/v1/workspaces/${workspace.id}/region-fields`)).json();expect(fields).toHaveLength(2);expect(fields.every((field:{metadata:{experimental_unit:unknown;condition:string}})=>field.metadata.experimental_unit===null&&field.metadata.condition==="Software test only")).toBe(true);await shot(page,"batch-registration-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await shot(page,"batch-registration-mobile.png");expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"batch-receipt.json"),JSON.stringify({passed:true,source:"Public BBBC013 DRAQ pixels repeated only for upload mapping/idempotence test; no new stain or biological replication claim.",logicalFields:2,attempts:3,retainedLogicalId:true,unknownIndependentUnitPreserved:true,pageErrors:errors},null,2));
});
