import {test,expect,type Page,type APIResponse} from "@playwright/test";
import {execFileSync} from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import {createRegionWorkspace,workspaceTestRuntime} from "./workspace-session";
import {expectGfpPreview} from "./image-preview";

const root=path.resolve(__dirname,"../../..");const {api,python,dataDir}=workspaceTestRuntime();
const evidence=process.env.CYTELLECT_SCREENSHOT_DIR;
async function json(response:Pick<APIResponse,"ok"|"json">){expect(response.ok()).toBeTruthy();return response.json();}
async function post(page:Page,url:string,data:unknown){return json(await page.request.post(api+url,{data,headers:{Origin:new URL(page.url()).origin,"X-Cytellect-Request":"1"}}));}
async function waitJob(page:Page,id:string){await expect.poll(async()=>{const job=await json(await page.request.get(`${api}/v1/jobs/${id}`));if(["failed","cancelled"].includes(job.state))throw Error(job.error);return job.state;},{timeout:120000,intervals:[500]}).toBe("succeeded");}
async function traceDetails(page:Page){const details=page.locator("details").filter({has:page.locator(":scope>summary",{hasText:"図に使った測定値"})});if(!await details.evaluate(el=>(el as HTMLDetailsElement).open))await details.locator(":scope>summary").click();return details;}
async function screenshot(page:Page,name:string){if(evidence){fs.mkdirSync(evidence,{recursive:true});await page.screenshot({path:path.join(evidence,name),fullPage:true});}}
async function imageBounds(page:Page){return page.getByTestId("image-canvas").locator("canvas").first().evaluate(canvas=>{const el=canvas as HTMLCanvasElement;const pixels=el.getContext("2d")!.getImageData(0,0,el.width,el.height).data;let left=el.width,top=el.height,right=-1,bottom=-1;for(let y=0;y<el.height;y++)for(let x=0;x<el.width;x++)if(pixels[(y*el.width+x)*4+3]>250){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}return {left,top,right,bottom,width:el.width,height:el.height};});}

test("saved generic observations trace exact historical masks and channels without losing drafts",async({page})=>{
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
 const workspace=await createRegionWorkspace(page,"Published-image source tracing");
 const scratch=fs.mkdtempSync(path.join(dataDir!,"trace-labels-"));const labelFile=path.join(scratch,"regions.tif");
 const raw=path.join(root,"fixtures/public/bbbc013/A01-gfp.tif");const dna=path.join(root,"fixtures/public/bbbc013/A01-dapi.tif");
 // Published pixels are unchanged; 26 rectangles are artificial identity/navigation fixtures, not cell segmentation.
 execFileSync(python,["-c","import sys,numpy as np,tifffile;a=tifffile.imread(sys.argv[1]);m=np.zeros(a.shape,dtype=np.uint32);[(m.__setitem__((slice(25+(i//7)*20,35+(i//7)*20),slice(25+(i%7)*20,35+(i%7)*20)),i+1)) for i in range(26)];tifffile.imwrite(sys.argv[2],m)",raw,labelFile]);
 const channels=[{channel_id:"signal",label:"FKHR-EGFP",stain:"FKHR-EGFP",identity_confirmed:true},{channel_id:"dna",label:"DRAQ",stain:"DRAQ",identity_confirmed:true}];
 const fields=[];
 for(let i=0;i<2;i++)fields.push(await json(await page.request.post(`${api}/v1/workspaces/${workspace.id}/region-fields`,{headers:{Origin:new URL(page.url()).origin,"X-Cytellect-Request":"1"},multipart:{specification:JSON.stringify({version:"1.0.0",channels,metadata:{sample:`Navigation fixture ${i+1}`}}),ch0:{name:"public-signal.tif",mimeType:"image/tiff",buffer:fs.readFileSync(raw)},ch1:{name:"public-dna.tif",mimeType:"image/tiff",buffer:fs.readFileSync(dna)},labels:{name:"test-regions.tif",mimeType:"image/tiff",buffer:fs.readFileSync(labelFile)}}})));
 const background={polygon:[[0,0],[15,0],[15,15],[0,15]],confirmed:true};
 const initial=await post(page,`/v1/workspaces/${workspace.id}/region-analyses`,{recipe:{id:"region-2d",version:"1.0.0",region_set_id:"regions",label:"Navigation regions",source:"imported"},backgrounds:Object.fromEntries(fields.map(f=>[f.id,{signal:background,dna:background}])),exclusions:[]});await waitJob(page,initial.job_id);
 const metadata=await post(page,`/v1/revisions/${initial.revision_id}/region-metadata`,{version:"1.0.0",fields:Object.fromEntries(fields.map(f=>[f.id,f.metadata]))});await waitJob(page,metadata.job_id);
 await post(page,`/v1/revisions/${metadata.revision_id}/review`,{});
 const described=await post(page,`/v1/revisions/${metadata.revision_id}/descriptive`,{mode:"descriptive",selection:{source:"region",region_set_id:"regions",channel_id:"signal",metric:"mean_corrected"},group_by:"field",plot:{preset:"nature-double",kind:"distribution",language:"en",width_inches:7,height_inches:3,font_size:7,x_label:"",y_label:"",group_order:[]}});await waitJob(page,described.job_id);
 const result=await json(await page.request.get(`${api}/v1/jobs/${described.job_id}/result`));expect(result.plot_data).toHaveLength(52);expect(result.plot_data[0].mask_revision_id).toBe(initial.revision_id);expect(result.revision_id).toBe(metadata.revision_id);
 const targetField=fields[1];const savedMask=await json(await page.request.get(`${api}/v1/revisions/${metadata.revision_id}/region-masks?field_id=${targetField.id}`));
 const edited=await post(page,`/v1/revisions/${metadata.revision_id}/region-edits`,{field_id:targetField.id,region_set_id:"regions",operation:"delete",ids:[26],polygon:[],expected_mask_revision_id:savedMask.metadata.mask_revision_id});await waitJob(page,edited.job_id);
 await page.reload();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await expectGfpPreview(page);
 await page.getByRole("button",{name:"DRAQ",exact:true}).click();await page.getByRole("button",{name:/02 分布と図/}).click();
 await page.getByLabel("表示する測定値",{exact:true}).selectOption("dna-integrated");await expect(page.getByLabel("保存済みの測定値",{exact:true})).toContainText("FKHR-EGFP");await expect(page.getByText("旧版の結果",{exact:true})).toBeVisible();
 let details=await traceDetails(page);await expect(details.locator("tbody tr")).toHaveCount(20);await details.getByRole("button",{name:"次の20件",exact:true}).click();await expect(details).toContainText("21–40 / 52 件");
 await details.getByLabel("図の視野で絞り込む",{exact:true}).selectOption(targetField.id);await expect(details).toContainText("1–20 / 26 件");await details.getByRole("button",{name:"次の20件",exact:true}).click();await expect(details.locator("tbody tr")).toHaveCount(6);
 await screenshot(page,"trace-table-desktop.png");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await screenshot(page,"trace-table-mobile.png");await page.setViewportSize({width:1440,height:1000});
 let currentDone!:()=>void;const done=new Promise<void>(resolve=>{currentDone=resolve;});let releaseCurrent!:()=>void;let currentEntered!:()=>void;const entered=new Promise<void>(resolve=>{currentEntered=resolve;});const release=new Promise<void>(resolve=>{releaseCurrent=resolve;});
 let holdRefresh=false;let refreshEntered!:()=>void;const refreshStarted=new Promise<void>(resolve=>{refreshEntered=resolve;});let releaseRefresh!:()=>void;const refreshRelease=new Promise<void>(resolve=>{releaseRefresh=resolve;});let refreshDone!:()=>void;const refreshed=new Promise<void>(resolve=>{refreshDone=resolve;});
 await page.route(`**/v1/workspaces/${workspace.id}`,async route=>{const response=await route.fetch();if(holdRefresh){refreshEntered();await refreshRelease;}await route.fulfill({response});if(holdRefresh)refreshDone();});
 await page.route(`**/v1/workspaces/${workspace.id}/current`,async route=>{const response=await route.fetch();currentEntered();await release;holdRefresh=true;await route.fulfill({response});currentDone();});
 await details.getByRole("button",{name:/領域 26 を画像で確認$/}).click();await entered;
 await expect(page.getByText("保存済みの領域を開いています。",{exact:false})).toBeVisible();expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(true);
 await expect(page.getByRole("button",{name:/01 画像と領域/}).click({timeout:500})).rejects.toThrow();releaseCurrent();await done;await refreshStarted;
 // Adoption alone is insufficient: editing remains locked until refreshed revision/config/masks settle.
 expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(true);await expect(page.getByText(/図に記録された領域 26 を表示しています/)).toHaveCount(0);
 releaseRefresh();await refreshed;await page.unroute(`**/v1/workspaces/${workspace.id}`);await page.unroute(`**/v1/workspaces/${workspace.id}/current`);
 try{await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("26");}catch(error){if(evidence){const current=await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}`));fs.writeFileSync(path.join(evidence,"trace-failure-state.json"),JSON.stringify({activeMatchesTarget:current.active_revision===metadata.revision_id,selected:await page.getByLabel("選択した領域ID",{exact:true}).inputValue(),notices:await page.locator('main [role="alert"], main [role="status"]').allTextContents(),locked:await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))},null,2));await screenshot(page,"trace-failure.png");}throw error;}await expect(page.getByText(/図に記録された領域 26 を表示しています/)).toBeVisible();await expectGfpPreview(page);
 expect((await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}`))).active_revision).toBe(metadata.revision_id);
 await expect(page.getByRole("button",{name:"FKHR-EGFP",exact:true})).toHaveClass(/segmentActive/);await expect(page.getByLabel("輪郭",{exact:true})).toBeChecked();await screenshot(page,"trace-selected-desktop.png");
 const fittedBounds=await imageBounds(page);for(let i=0;i<4;i++)await page.getByRole("button",{name:"拡大",exact:true}).click();await expect(page.getByRole("button",{name:"全体を表示 · 244%",exact:true})).toBeVisible();
 const canvasBox=await page.getByTestId("image-canvas").locator("canvas").first().boundingBox();expect(canvasBox).not.toBeNull();await page.mouse.move(canvasBox!.x+canvasBox!.width*.6,canvasBox!.y+canvasBox!.height*.6);await page.mouse.down();await page.mouse.move(canvasBox!.x+canvasBox!.width*.6+100,canvasBox!.y+canvasBox!.height*.6+60,{steps:8});await page.mouse.up();
 await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);await details.getByLabel("図の視野で絞り込む",{exact:true}).selectOption(targetField.id);await details.getByRole("button",{name:"次の20件",exact:true}).click();await details.getByRole("button",{name:/領域 26 を画像で確認$/}).click();await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("26");await expectGfpPreview(page);await expect(page.getByRole("button",{name:"全体を表示 · 100%",exact:true})).toBeVisible();expect(await imageBounds(page)).toEqual(fittedBounds);await screenshot(page,"trace-restored-view-desktop.png");
 await page.getByRole("button",{name:"DRAQ",exact:true}).click();await expect(page.getByText(/図に記録された領域 26 を表示しています/)).toHaveCount(0);
 await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);await details.getByRole("button",{name:/領域 1 を画像で確認$/}).first().click();await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("1");await page.getByLabel("選択した領域ID",{exact:true}).fill("2");await expect(page.getByText(/図に記録された領域 1 を表示しています/)).toHaveCount(0);
 // Existing field-only source links share the same lock and recover from a failed adoption.
 await post(page,`/v1/workspaces/${workspace.id}/current`,{revision_id:edited.revision_id});await page.reload();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await page.getByRole("button",{name:/02 分布と図/}).click();
 await page.route(`**/v1/workspaces/${workspace.id}/current`,route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"request_failed"})}));await page.getByRole("button",{name:"この解析版の画像を確認",exact:true}).first().click();await expect(page.locator("main").getByRole("alert")).toContainText("保存済みの視野を開けませんでした");await expect.poll(()=>page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(false);await page.unroute(`**/v1/workspaces/${workspace.id}/current`);
 let fieldDone!:()=>void;const fieldDonePromise=new Promise<void>(resolve=>{fieldDone=resolve;});let releaseField!:()=>void;let enteredField!:()=>void;const fieldEntered=new Promise<void>(resolve=>{enteredField=resolve;});const fieldRelease=new Promise<void>(resolve=>{releaseField=resolve;});
 await page.route(`**/v1/workspaces/${workspace.id}/current`,async route=>{const response=await route.fetch();enteredField();await fieldRelease;await route.fulfill({response});fieldDone();});await page.getByRole("button",{name:"この解析版の画像を確認",exact:true}).first().click();await fieldEntered;
 expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(true);await expect(page.getByRole("button",{name:/01 画像と領域/}).click({timeout:500})).rejects.toThrow();releaseField();await fieldDonePromise;await page.unroute(`**/v1/workspaces/${workspace.id}/current`);await expect(page.getByRole("button",{name:"追加",exact:true})).toBeVisible();
 // Draft polygon and even unapplied coordinate text must survive a blocked trace action.
 await page.getByRole("button",{name:"追加",exact:true}).click();await page.getByText("座標から多角形を指定",{exact:true}).click();await page.getByLabel("頂点（x,y を空白または改行で区切る）").fill("200,200 215,200 215,215");await page.getByRole("button",{name:"座標を反映",exact:true}).click();
 await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);await expect(details.getByRole("button",{name:/を画像で確認$/}).first()).toBeDisabled();
 await page.getByRole("button",{name:/01 画像と領域/}).click();await expect(page.getByLabel("頂点（x,y を空白または改行で区切る）")).toHaveValue("200,200 215,200 215,215");await expect(page.getByRole("button",{name:/領域を保存・再測定 · 3 点/})).toBeVisible();await page.getByRole("button",{name:"選択",exact:true}).click();
 await page.getByLabel("選択した領域ID",{exact:true}).fill("2");await page.getByLabel("領域の除外理由",{exact:true}).fill("Draft exclusion fixture");await page.getByRole("button",{name:"選択領域を除外指定",exact:true}).click();await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);await expect(details.getByRole("button",{name:/を画像で確認$/}).first()).toBeDisabled();await page.getByRole("button",{name:/01 画像と領域/}).click();await expect(page.getByLabel("領域の除外理由",{exact:true})).toHaveValue("Draft exclusion fixture");
 // A valid-looking saved ID missing from the exact historical mask must not adopt/select anything.
 await page.route(`**/v1/jobs/${described.job_id}/result`,async route=>{const response=await route.fetch();const body=await response.json();body.plot_data[0]={...body.plot_data[0],region_id:99999,observation_id:JSON.stringify([body.plot_data[0].field_id,"regions",99999])};await route.fulfill({response,json:body});});
 await page.reload();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);await details.getByRole("button",{name:/領域 99999 を画像で確認$/}).click();await expect(page.locator("main").getByRole("alert")).toContainText("この図に記録された領域を確認できません");
 expect((await json(await page.request.get(`${api}/v1/workspaces/${workspace.id}`))).active_revision).toBe(metadata.revision_id);await page.unroute(`**/v1/jobs/${described.job_id}/result`);
 await page.reload();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await page.getByRole("button",{name:"DRAQ",exact:true}).click();await page.getByRole("button",{name:/02 分布と図/}).click();await page.getByLabel("表示する測定値",{exact:true}).selectOption("area_px");
 const areaPending=page.waitForResponse(response=>response.url().endsWith("/descriptive")&&response.request().method()==="POST");await page.getByRole("button",{name:"分布図を作成",exact:true}).click();const area=await json(await areaPending);await waitJob(page,area.job_id);await expect(page.getByLabel("保存済みの測定値",{exact:true})).toContainText("面積 / px²");details=await traceDetails(page);await expect(details).toContainText("面積測定にはチャンネルを使用していません");await details.getByRole("button",{name:/領域 2 を画像で確認$/}).first().click();await expect(page.getByLabel("選択した領域ID",{exact:true})).toHaveValue("2");await expect(page.getByRole("button",{name:"DRAQ",exact:true})).toHaveClass(/segmentActive/);await expect(page.getByText(/面積測定にはチャンネルを使用していません。表示: DRAQ/)).toBeVisible();
 // A navigation refresh deadline must not unlock an uncertain editor or apply a late response to a new draft.
 await post(page,`/v1/workspaces/${workspace.id}/current`,{revision_id:edited.revision_id});await page.reload();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await page.getByRole("button",{name:/02 分布と図/}).click();details=await traceDetails(page);
 let releaseLate!:()=>void;const lateRelease=new Promise<void>(resolve=>{releaseLate=resolve;});let lateDone!:()=>void;const lateFinished=new Promise<void>(resolve=>{lateDone=resolve;});
 await page.route(`**/v1/workspaces/${workspace.id}`,async route=>{const response=await route.fetch();await lateRelease;try{await route.fulfill({response});}finally{lateDone();}});
 await details.getByRole("button",{name:/領域 2 を画像で確認$/}).first().click();await expect(page.locator("main").getByRole("alert")).toContainText("採用中の解析版を確認できません");expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(true);await expect(page.getByRole("button",{name:/01 画像と領域/}).click({timeout:500})).rejects.toThrow();
 releaseLate();await lateFinished;await page.unroute(`**/v1/workspaces/${workspace.id}`);expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(true);await page.getByRole("button",{name:"作業一覧へ戻る",exact:true}).click();await page.getByRole("button",{name:new RegExp(workspace.title)}).click();await expect(page.getByRole("button",{name:"追加",exact:true})).toBeVisible();expect(await page.locator('nav[aria-label="解析工程"]').evaluate(el=>!!el.closest("[inert]"))).toBe(false);
 expect(errors).toEqual([]);
 if(evidence)fs.writeFileSync(path.join(evidence,"trace-browser-receipt.json"),JSON.stringify({dataset:"BBBC013 A01 public DRAQ/FKHR-EGFP pixels; 26 artificial navigation rectangles per duplicate field, not a segmentation or replication claim",savedObservations:52,maskReuseRevisionDistinct:true,historicalDeletedRegionRestored:true,channelAndMetricSourcePreserved:true,paginationAndFieldFilter:true,delayedRegionAndFieldAdoptionLockNavigation:true,refreshCommitLock:true,lateRefreshRecoveryPreservesEditingBoundary:true,sameFieldZoomPanRestoresFullFit:true,fieldAdoptionFailureRecovers:true,draftPolygonAndExclusionRetained:true,staleTraceNoticeCleared:true,unknownRegionRejected:true,areaHasNoMeasurementChannel:true,errors},null,2));
});
