import {expect, test} from "@playwright/test";
import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import {mkdir, readFile} from "node:fs/promises";
import path from "node:path";
import type {WorkspaceRun,WorkspaceSelection} from "../src/lib/workspace/api-adapter";

/** Registered real input checks execution/wiring, not biological accuracy of the candidates. */
test("nuclear and nucleolar candidates retain source identity and explicit adoption",async({page})=>{
  const inputs=process.env.CYTELLECT_REAL_INPUTS,output=process.env.CYTELLECT_REAL_OUTPUT;
  const python=process.env.CYTELLECT_TEST_PYTHON,data=process.env.CYTELLECT_TEST_DATA_DIR,api=process.env.CYTELLECT_TEST_API_ORIGIN;
  if(process.env.CYTELLECT_REQUIRE_REAL_FIJI==="1")for(const value of [inputs,output,python,data,api])expect(value).toBeTruthy();
  test.skip(!inputs||!output||!python||!data||!api,"Requires explicitly configured isolated Fiji runtime and registered public inputs");
  await mkdir(output!,{recursive:true});
  const manifest=JSON.parse(await readFile(path.join(inputs!,"manifest.json"),"utf8"));
  const original=["a9-actin.tif","a9-dna.tif"];
  const bytes=await Promise.all(original.map(name=>readFile(path.join(inputs!,name))));
  bytes.forEach((value,index)=>expect(createHash("sha256").update(value).digest("hex")).toBe(manifest.files[original[index]]));
  const token=execFileSync(python!,["-B","-c","import os;from pathlib import Path;from cytellect_api.db import Store;print(Store(Path(os.environ['CYTELLECT_TEST_DATA_DIR'])).invite(3600))"],{encoding:"utf8",env:process.env,stdio:["ignore","pipe","ignore"]}).trim();
  const redeemed=await page.request.post(`${api}/v1/invitations/redeem`,{headers:{Origin:process.env.CYTELLECT_WEB_URL!,"X-Cytellect-Request":"1"},data:{token}});
  expect(redeemed.ok()).toBeTruthy();
  const loaded=page.waitForResponse(response=>new URL(response.url()).pathname==="/v1/workspaces"&&response.request().method()==="GET");
  await page.goto("/workspace");await loaded;
  await expect(page.getByRole("button",{name:"新しいワークスペース",exact:true})).toBeEnabled();
  await page.getByRole("button",{name:"新しいワークスペース",exact:true}).click();
  const selectionWrites:string[]=[],runRequests:Array<{target:string;purpose:string}>=[];
  let paidCalls=0;
  page.on("request",request=>{const p=new URL(request.url()).pathname;if(request.method()!=="POST")return;if(p.endsWith("/selection")||p.endsWith("/accept"))selectionWrites.push(p);if(p.endsWith("/runs"))runRequests.push(request.postDataJSON());if(p.endsWith("/proposal-drafts"))paidCalls++;});
  const created=page.waitForResponse(response=>new URL(response.url()).pathname==="/v1/workspaces"&&response.request().method()==="POST");
  await page.getByTestId("file-input").setInputFiles(bytes.map((buffer,index)=>({name:`a9_c${index+1}.tif`,mimeType:"image/tiff",buffer})));
  const wid=(await (await created).json()).id as string;
  await expect(page.getByRole("button",{name:"染色対応",exact:true})).toBeEnabled();
  expect(runRequests).toHaveLength(0);
  await expect(page.getByLabel("AIへの指示",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"染色対応",exact:true}).click();
  // Roles are explicit; c2 alone does not establish the nuclear stain.
  await page.getByLabel("c1の染色名").fill("F-actin");
  await page.getByLabel("c1の役割").selectOption("measure");
  await page.getByLabel("c2の染色名").fill("DNA");
  await page.getByLabel("c2の役割").selectOption("nuclear");
  await page.getByRole("button",{name:"保存",exact:true}).click();
  await expect(page.getByText("核 · 検出候補",{exact:true})).toBeVisible({timeout:300000});
  expect(runRequests).toEqual([{request_id:expect.any(String),spec_version:expect.any(Number),target:"nuclei",field_ids:[expect.any(String)],purpose:"preview"}]);
  const selection=async()=>{const response=await page.request.get(`${api}/v1/workspaces/${wid}/selection`);expect(response.ok()).toBeTruthy();return await response.json() as WorkspaceSelection;};
  expect((await selection()).entries[0].target_revisions?.nuclei).toBeUndefined();
  await page.getByRole("button",{name:"DNA · c2",exact:true}).click();
  const image=page.getByRole("img",{name:/DNA/}).first();
  const modes=page.getByRole("navigation",{name:"作業の切替"});
  await expect(image).toBeVisible();
  expect(await image.locator("[data-region]").count()).toBeGreaterThan(0);
  const before=selectionWrites.length;
  await modes.getByRole("button",{name:"統計",exact:true}).click();
  await expect(page.getByRole("region",{name:"測定結果の統計解析"})).toBeVisible();
  await modes.getByRole("button",{name:"画像",exact:true}).click();
  await expect(image).toBeVisible();
  expect(selectionWrites.length).toBe(before);
  await page.screenshot({path:path.join(output!,"connected-nuclear-candidate.png")});
  await page.getByRole("button",{name:"候補を採用",exact:true}).click();
  await expect(page.getByText("核 · 検出候補",{exact:true})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"測定",exact:true})).toBeEnabled();
  const nuclear=(await selection()).entries[0].target_revisions!.nuclei;
  expect(nuclear).toBeTruthy();
  const inspector=page.getByRole("complementary",{name:"画像解析",exact:true});
  await inspector.getByRole("combobox",{name:"領域",exact:true}).selectOption("nucleoli");
  const adoptedCount=selectionWrites.length;
  await inspector.getByRole("combobox",{name:"核小体の定義",exact:true}).selectOption("dapi_poor");
  await expect(page.getByText("核小体 · 検出候補",{exact:true})).toBeVisible({timeout:300000});
  expect(selectionWrites.length).toBe(adoptedCount);
  const runsResponse=await page.request.get(`${api}/v1/workspaces/${wid}/runs`);expect(runsResponse.ok()).toBeTruthy();
  const runs=await runsResponse.json() as WorkspaceRun[];
  const nucleolar=runs.find(value=>value.target==="nucleoli"&&value.state==="succeeded")!;
  expect(nucleolar.steps.find(value=>value.target==="nuclei")).toMatchObject({state:"reused",revision_id:nuclear});
  expect(nucleolar.steps.find(value=>value.target==="nucleoli")?.recipe).toMatchObject({defining_channel_id:"c2",detector:{engine:"cytellect-nucleolar-v2",source:"dapi_poor"}});
  await page.screenshot({path:path.join(output!,"connected-nucleolar-candidate.png")});
  await page.getByRole("button",{name:"候補を採用",exact:true}).click();
  await expect(page.getByText("核小体 · 検出候補",{exact:true})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"測定",exact:true})).toBeEnabled();
  const nucleoli=(await selection()).entries[0].target_revisions!.nucleoli;
  expect(nucleoli).toBeTruthy();
  await inspector.getByRole("combobox",{name:"領域",exact:true}).selectOption("nucleoplasm");
  await page.getByRole("button",{name:"測定",exact:true}).click();
  await expect(page.getByRole("button",{name:"測定",exact:true})).toBeEnabled({timeout:300000});
  const final=(await selection()).entries[0].target_revisions!;
  expect(final.nuclei).toBe(nuclear);expect(final.nucleoli).toBe(nucleoli);expect(final.nucleoplasm).toBeTruthy();
  const revisionResponse=await page.request.get(`${api}/v1/revisions/${final.nucleoplasm}`);expect(revisionResponse.ok()).toBeTruthy();
  expect((await revisionResponse.json()).config.recipe).toMatchObject({compartment:"nucleoplasm",nuclear_revision_id:nuclear,nucleolar_revision_id:nucleoli});
  await modes.getByRole("button",{name:"統計",exact:true}).click();
  await expect(page.getByRole("region",{name:"測定結果の統計解析"})).toBeVisible();
  await page.screenshot({path:path.join(output!,"connected-compartment-statistics.png")});
  expect(paidCalls).toBe(0);
});
