"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { LOCAL_MODE } from "@/lib/api";
import { formatValue } from "@/lib/types";
import styles from "./workspace.module.css";
const NavigationLink=LOCAL_MODE?"a":Link;
type SampleInfo={id:string;title:string;subtitle:string;preview:string;data:string;source:string;license:string};
type Column={key:string;label:string;unit?:string};
type Sample={attribution?:string;dataset:string;source:string;license:string;channel:string;width:number;height:number;quantification:string;image_id:string;labels:{id:number;points:number[][]}[];nucleolar_labels?:{id:number;points:number[][]}[];measurements:Record<string,number>[];columns?:Column[];channel_previews?:{label:string;path:string}[];engine?:{engine:string;model:string};mapping_note?:string;notes?:string[]};
const defaultColumns:Column[]=[{key:"area_px",label:"核面積",unit:"px²"},{key:"dna_mean_raw",label:"DNA 平均輝度"},{key:"dna_integral_raw",label:"DNA 積算輝度"}];
export default function DemoWorkspace(){
 const [samples,setSamples]=useState<SampleInfo[]>([]);const [sampleId,setSampleId]=useState("");const [sample,setSample]=useState<Sample|null>(null);const [outlines,setOutlines]=useState(true);const [selected,setSelected]=useState(1);const [view,setView]=useState("image");const [gain,setGain]=useState(1);const [channelIndex,setChannelIndex]=useState(0);const [loadError,setLoadError]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch("/demo/index.json",{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then((items:SampleInfo[])=>{setSamples(items);setSampleId(items[0]?.id||"");}).catch(()=>{if(!c.signal.aborted)setLoadError(true);});return()=>c.abort();},[]);
 const info=samples.find(s=>s.id===sampleId);
 useEffect(()=>{if(!info)return;const c=new AbortController();setSample(null);setLoadError(false);fetch(info.data,{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then((data:Sample)=>{setSample(data);setSelected(data.measurements[0]?.nucleus_id||1);setChannelIndex(0);}).catch(()=>{if(!c.signal.aborted)setLoadError(true);});return()=>c.abort();},[info]);
 const columns=sample?.columns||defaultColumns;const cell=sample?.measurements.find(c=>c.nucleus_id===selected);
 const previews=sample?.channel_previews|| (info?[{label:sample?.channel||"DNA",path:info.preview}]:[]);
 function save(){if(!sample)return;const keys=["nucleus_id",...columns.map(c=>c.key)];const csv=[keys.join(","),...sample.measurements.map(c=>keys.map(k=>String(c[k]??"")).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="cytellect-"+sample.dataset+"-measurements.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className={styles.demoPage}>
  <header className={styles.header}><NavigationLink href="/" className={styles.brand} style={{textDecoration:"none"}}><span className={styles.brandMark}><i/><i/><i/></span>cytellect</NavigationLink><div className={styles.headerMeta}><span className={styles.statusPill}>PUBLIC DATA WORKSPACE</span><NavigationLink href="/" className={styles.secondary}>{LOCAL_MODE?"ワークスペース":"招待で接続"}</NavigationLink></div></header>
  <section className={styles.demoIntro}><div><span className={styles.eyebrow}>EXPLORE CYTELLECT</span><h1>公開画像の解析</h1><p>核を選択すると、領域の測定値を表示します。</p></div><span className={styles.demoNote}>公開実画像の解析済みサンプルです。{LOCAL_MODE?"自身の画像はワークスペースから登録できます。":"自身の画像には非公開の解析サーバーが必要です。"}</span></section>
  <div className={styles.demoContent}><label className={styles.mobileSamplePicker}>画像<select aria-label="画像" value={sampleId} onChange={e=>setSampleId(e.target.value)}>{samples.map(s=><option key={s.id} value={s.id}>{s.title} · {s.subtitle}</option>)}</select></label><nav className={styles.tabs}><button className={view==="image"?styles.activeTab:""} onClick={()=>setView("image")}>01 <b>画像と領域</b></button><button className={view==="measurements"?styles.activeTab:""} onClick={()=>setView("measurements")}>02 <b>測定値</b></button><span className={styles.tabStatus}>{sample?`${sample.width} × ${sample.height} px · ${sample.channel}`:""}</span></nav>
   {loadError?<div role="alert" className={styles.error}>公開サンプルを読み込めませんでした。</div>:<div className={styles.demoGrid}>
    <aside className={styles.demoSidebar}><span className={styles.sectionNumber}>PUBLIC IMAGES</span>{samples.map((s,i)=><button className={sampleId===s.id?styles.activeField:styles.field} key={s.id} onClick={()=>setSampleId(s.id)}><div><span className={styles.fieldNumber}>{String(i+1).padStart(2,"0")}</span><b>{s.title}</b></div><small>{s.subtitle}</small><div className={styles.fieldBadges}><span>公開実画像</span></div></button>)}<div className={styles.demoSummary}><span>WORKFLOW</span><p>✓ 公開画像を登録</p><p>✓ Fijiで核を検出</p><p>✓ 原画像から測定</p><p>○ サーバーで再解析</p></div></aside>
    <section className={styles.viewer}>{!sample?<div className={styles.canvasLoading}>公開画像を読み込んでいます…</div>:view==="image"?<><div className={styles.viewerToolbar}><div className={styles.segmented}>{previews.map((p,i)=><button key={p.label} className={channelIndex===i?styles.segmentActive:""} onClick={()=>setChannelIndex(i)}>{p.label}</button>)}</div><label className={styles.inlineLabel}>表示<input aria-label="サンプル表示ゲイン" type="range" min={.5} max={2.5} step={.1} value={gain} onChange={e=>setGain(Number(e.target.value))}/></label><label className={styles.checkbox}><input type="checkbox" checked={outlines} onChange={e=>setOutlines(e.target.checked)}/>輪郭</label></div>
     <div className={styles.demoImage}><div className={styles.realImageFrame} style={{aspectRatio:`${sample.width} / ${sample.height}`}}><img src={previews[channelIndex]?.path||info?.preview} alt={`${sample.dataset} の公開実画像（${sample.channel}）`} style={{filter:`brightness(${gain})`}}/><svg viewBox={`0 0 ${sample.width} ${sample.height}`} role="group" aria-label="検出した核の輪郭">{sample.labels.map((m,i)=><polygon key={i} points={m.points.map(p=>p.join(",")).join(" ")} stroke={outlines?(m.id===selected?"#ffffff":"#80bba0"):"none"} fill={m.id===selected?"rgba(255,255,255,.15)":"transparent"} strokeWidth={m.id===selected?1.8:.8} onClick={()=>setSelected(m.id)} tabIndex={0} aria-label={"核 "+m.id} role="button" onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(m.id);}}}/>)}{outlines&&sample.nucleolar_labels?.map((m,i)=><polygon key={i} points={m.points.map(p=>p.join(",")).join(" ")} stroke="#f1b766" strokeWidth={1} fill="transparent" pointerEvents="none"/>)}</svg></div><div className={styles.canvasBottom}><div className={styles.legend}><span style={{color:"#80bba0"}}>● 核</span>{!!sample.nucleolar_labels?.length&&<span style={{color:"#f2bb67"}}>● 核小体候補</span>}</div><span>核をクリックして選択</span><span>{sample.measurements.length} nuclei</span></div></div>
    </>:<div className={styles.demoTable}><div className={styles.sectionHeader}><h2>領域ごとの測定値</h2><button className={styles.secondary} onClick={save}>CSV ↓</button></div><div className={styles.tableWrap}><table><thead><tr><th>核ID</th>{columns.map(c=><th key={c.key}>{c.label} {c.unit}</th>)}</tr></thead><tbody>{sample.measurements.map(c=><tr key={c.nucleus_id} onClick={()=>setSelected(c.nucleus_id)} style={{background:c.nucleus_id===selected?"#edf4f0":undefined}}><td><button className={styles.linkButton} onClick={()=>setSelected(c.nucleus_id)}>{String(c.nucleus_id).padStart(2,"0")}</button></td>{columns.map(col=><td key={col.key}>{formatValue(c[col.key])}</td>)}</tr>)}</tbody></table></div></div>}</section>
    <aside className={styles.demoInspector}><span className={styles.sectionNumber}>SELECTED OBJECT</span><div className={styles.objectTitle}><h2>Nucleus {String(selected).padStart(2,"0")}</h2><span className={styles.statusPill}>自動検出</span></div><div className={styles.objectNavigation}><button disabled={selected<2} onClick={()=>setSelected(v=>v-1)} aria-label="前の核">←</button><label className={styles.objectIdLabel}>核ID<input aria-label="サンプル核ID" type="number" min={1} max={sample?.measurements.length||1} value={selected} onChange={e=>{const n=Number(e.target.value);if(sample?.measurements.some(c=>c.nucleus_id===n))setSelected(n);}}/></label><button disabled={selected===(sample?.measurements.length||1)} onClick={()=>setSelected(v=>v+1)} aria-label="次の核">→</button></div>
     <dl className={styles.objectMetrics}>{columns.map(c=><div key={c.key}><dt>{c.label}</dt><dd>{formatValue(cell?.[c.key])} {c.unit&&<small>{c.unit}</small>}</dd></div>)}</dl>
     <button className={styles.secondary} onClick={save} disabled={!sample}>測定表を保存 ↓</button>
     {sample?.mapping_note&&<p className={styles.mappingNote}>{sample.mapping_note}</p>}<div className={styles.datasetCredit}><span>SOURCE</span><a href={info?.source} target="_blank" rel="noreferrer">{info?.title} ↗</a><small>{info?.license}</small>{sample?.attribution&&<small>{sample.attribution}</small>}</div>
     <details className={styles.demoMethod}><summary>解析条件と制約</summary><p>{sample?.quantification}</p><p>{sample?.engine?.engine} · {sample?.engine?.model}</p>{sample?.notes?.map((n,i)=><p key={i}>{n}</p>)}<p>保存済みの解析結果を表示しています。この画面ではFijiの再実行、画像のアップロード、群間検定は行いません。</p></details>
    </aside>
   </div>}
  </div><footer className={styles.demoFooter}><span>CYTELLECT / DEVELOPMENT PREVIEW</span><span>Original pixels. Traceable measurements.</span></footer>
 </main>;
}
