"use client";
import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { download, post, request } from "@/lib/api";
import { usePrivateImage } from "@/lib/usePrivateImage";
import { availableMetricIds, fieldRoles, metricLabels, type Field, type Job, type Revision } from "@/lib/types";
import styles from "./workspace.module.css";
import { ComparisonTable, ModelResult, ResultWarnings, SensitivityResults, type StatisticalResult } from "./StatisticalResults";
import DescriptivePanel from "./DescriptivePanel";
type NumericTable={id:string;row_count:number;metadata:{groups?:string[];conditions?:string[]}};
type Props={wid:string;revision?:Revision;jobs:Job[];fields:Field[];revisions:Revision[];dirty:boolean;blocked:boolean;run:(fn:()=>Promise<void>)=>void;onInspectField?:(fieldId:string,revisionId:string)=>void};
export default function StatisticsPanel(props:Props){
 const [view,setView]=useState<"descriptive"|"comparison">("descriptive");
 const {revision,jobs,fields,dirty,blocked,run}=props;
 const included=fields.filter(f=>revision?.config.field_ids?.includes(f.id));
 const metrics=availableMetricIds({hasGfp:!!included.length&&included.every(f=>fieldRoles(f).includes("gfp")),hasNcl:revision?.config.recipe.id!=="gfp-nuclear-2d"&&!!included.length&&included.every(f=>fieldRoles(f).includes("ncl")),legacy:revision?.config.recipe.id==="ncl-legacy-rgb",calibrated:!!included.length&&included.every(f=>!!f.metadata.pixel_size_um)});
 return <div><div className={styles.downloadBar} role="group" aria-label="図の目的"><button className={view==="descriptive"?styles.primary:styles.secondary} aria-pressed={view==="descriptive"} onClick={()=>setView("descriptive")}>測定値と分布</button><button className={view==="comparison"?styles.primary:styles.secondary} aria-pressed={view==="comparison"} onClick={()=>setView("comparison")}>群間比較・関連解析</button></div>{view==="descriptive"?<DescriptivePanel planSelection={revision?.config.plan_resolution} revisionId={revision?.id} reviewed={!!revision?.reviewed} options={metrics.map(metric=>({id:metric,label:metricLabels[metric],selection:{source:"legacy-cell",metric}}))} jobs={jobs} dirty={dirty} blocked={blocked} run={run} fieldLabels={Object.fromEntries(fields.map((field,i)=>[field.id,`画像一覧の視野 ${i+1} · ${field.metadata.sample||"試料未記録"}`]))} revisionLabels={Object.fromEntries(props.revisions.map((rev,i)=>[rev.id,`解析版 ${i+1}`]))} onInspectField={props.onInspectField}/>:<ComparisonPanel {...props}/>}</div>;
}
function ComparisonPanel({wid,revision,jobs,fields,revisions,dirty,blocked,run}:Props){
 const qc=useQueryClient();
 const [metric,setMetric]=useState("ncl_log2_nucleoplasm_over_nucleoli");const [mode,setMode]=useState("experimental-unit");const [design,setDesign]=useState("unselected");const paired=design==="paired";const [confirmed,setConfirmed]=useState(false);const [kind,setKind]=useState("distribution");const [language,setLanguage]=useState("en");const [baseline,setBaseline]=useState("");const [targets,setTargets]=useState<string[]>([]);const [family,setFamily]=useState("baseline");const [customComparisons,setCustomComparisons]=useState("");const [selectedJob,setSelectedJob]=useState("");
 const [preset,setPreset]=useState("nature-single");const [highRegions,setHighRegions]=useState<number[]>([]);const [width,setWidth]=useState(7);const [height,setHeight]=useState(3);const [font,setFont]=useState(7);const [xLabel,setXLabel]=useState("");const [yLabel,setYLabel]=useState("");const [order,setOrder]=useState("");const [thresholds,setThresholds]=useState("");const [completeDates,setCompleteDates]=useState(false);const [transform,setTransform]=useState("positive-log2");const [source,setSource]=useState("images");
 const [regionRevisions,setRegionRevisions]=useState<string[]>([]);
 const alternateRegions=revisions.filter(r=>r.id!==revision?.id&&r.state==="succeeded"&&r.reviewed&&r.config.recipe.id==="ncl-native-2d");
 useEffect(()=>{setRegionRevisions([]);setDesign("unselected");setConfirmed(false);},[revision?.id,source]);
 const tables=useQuery({queryKey:["tables",wid],queryFn:()=>request<NumericTable[]>(`/v1/workspaces/${wid}/tables`)});
 const table=tables.data?.find(t=>t.id===source);
 const includedFields=fields.filter(f=>revision?.config.field_ids?.includes(f.id));const hasGfp=!!includedFields.length&&includedFields.every(f=>fieldRoles(f).includes("gfp"));const hasNcl=revision?.config.recipe.id!=="gfp-nuclear-2d"&&!!includedFields.length&&includedFields.every(f=>fieldRoles(f).includes("ncl"));const canGfpRelate=source==="images"&&hasGfp&&!metric.startsWith("gfp_");
 const metricIds=availableMetricIds({hasGfp,hasNcl,legacy:revision?.config.recipe.id==="ncl-legacy-rgb",calibrated:!!includedFields.length&&includedFields.every(f=>!!f.metadata.pixel_size_um)});
 const groups=useMemo(()=>source==="images"?[...new Set(fields.filter(f=>!revision?.config.field_ids||revision.config.field_ids.includes(f.id)).map(f=>f.metadata.condition))]:table?.metadata?.groups||table?.metadata?.conditions||[],[source,fields,table,revision]);
 useEffect(()=>{setBaseline(groups[0]||"");setTargets(groups.slice(1));},[groups]);
 useEffect(()=>{if(revision?.config.plan_resolution){setMetric(revision.config.plan_resolution.metric);setTransform("positive-log2");}else if(revision?.config.recipe.id==="ncl-legacy-rgb"){setMetric("ncl_legacy_release");setTransform("legacy-log2p1");}else{setMetric(revision?.config.recipe.id==="gfp-nuclear-2d"?"gfp_mean_corrected":"ncl_log2_nucleoplasm_over_nucleoli");setTransform("positive-log2");}},[revision?.id,revision?.config.plan_resolution,revision?.config.recipe.id]);
 useEffect(()=>{if(!metricIds.includes(metric)&&metricIds.length&&!revision?.config.plan_resolution){const preferred=revision?.config.recipe.id==="gfp-nuclear-2d"?"gfp_mean_corrected":revision?.config.recipe.id==="ncl-legacy-rgb"?"ncl_legacy_release":"ncl_log2_nucleoplasm_over_nucleoli";setMetric(metricIds.includes(preferred)?preferred:metricIds[0]);}},[metricIds,metric,revision?.config.recipe.id,revision?.config.plan_resolution]);
 useEffect(()=>{if(!canGfpRelate){setMode("experimental-unit");setKind(k=>k==="scatter"?"distribution":k);}},[canGfpRelate]);
 const available=jobs.filter(j=>j.analysis_mode!=="descriptive"&&(source==="images"?j.kind==="statistics":j.kind==="table-statistics"&&j.revision_id===source)&&j.state==="succeeded").toSorted((a,b)=>b.created-a.created);
 const job=available.find(j=>j.id===selectedJob)||available.find(j=>j.revision_id===revision?.id)||available[0];
 const result=useQuery({queryKey:["statistics",job?.id],queryFn:()=>request<StatisticalResult>(`/v1/jobs/${job!.id}/result`),enabled:!!job});
 const image=usePrivateImage(job?`/v1/jobs/${job.id}/files/figure.png`:null);
 async function generate(){
  const comparisons=family==="baseline"?targets.map(target=>[baseline,target]):customComparisons.split("\n").filter(v=>v.trim()).map(v=>v.split(",").map(x=>x.trim()));
  const body={metric:source==="images"?metric:"value",mode,baseline,comparisons,paired:mode==="experimental-unit"&&paired,independent_units_confirmed:confirmed,comparison_family:family,gfp_transform:transform,sensitivity_gfp_thresholds:hasGfp&&source==="images"&&thresholds.trim()?thresholds.split(",").map(Number):[],sensitivity_region_revision_ids:source==="images"&&revision?.config.recipe.id==="ncl-native-2d"?regionRevisions:[],sensitivity_complete_dates:source==="images"&&completeDates,sensitivity_legacy_high_regions:source==="images"&&revision?.config.recipe.id==="ncl-legacy-rgb"?highRegions:[],plot:{preset,kind,language,width_inches:width,height_inches:height,font_size:font,x_label:xLabel,y_label:yLabel,group_order:order.trim()?order.split(",").map(v=>v.trim()):[]}};
  const response=await post<{job_id:string}>(source==="images"?`/v1/revisions/${revision!.id}/statistics`:`/v1/tables/${source}/statistics`,body);setSelectedJob(response.job_id);
 }
 return <section className={styles.statistics}>
  <div className={styles.statsControls}><h2>統計解析</h2><p className={styles.small}>細胞数、視野数、独立実験単位数を区別します。1匹から撮った10視野は10匹の反復ではありません。撮影日だけで独立性は決まりません。</p>
   <label>解析するデータ<select aria-label="解析するデータ" value={source} onChange={e=>setSource(e.target.value)}><option value="images">採用中の画像解析版</option>{tables.data?.map((t,i)=><option value={t.id} key={t.id}>数値表 {i+1} · {t.row_count} 行</option>)}</select></label>
   <details className={styles.numericImport}><summary>測定済み数値CSVを取り込む</summary><p className={styles.small}>RNA・DNAなどの測定済み値を比較します。必要列：condition, experimental_unit, sample, field_id, acquisition_date, value。任意列：pair, repeat_length。装置固有の前処理は行いません。</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);run(async()=>{const r=await request<{table_id:string}>(`/v1/workspaces/${wid}/tables`,{method:"POST",body:data});await qc.invalidateQueries({queryKey:["tables",wid]});setSource(r.table_id);form.reset();});}}><label>数値CSV<input type="file" name="file" accept=".csv" required/></label><button className={styles.secondary} disabled={blocked}>数値表を登録</button></form></details>
   {source==="images"&&<label>指標<select aria-label="指標" value={metricIds.includes(metric)?metric:""} onChange={e=>setMetric(e.target.value)}><option value="">測定値を選択してください</option>{metricIds.map(value=><option value={value} key={value}>{metricLabels[value]}</option>)}</select></label>}
   {source==="images"&&revision?.config.plan_resolution&&(!metricIds.includes(metric)?<p className={styles.notice}>採用計画の指標をこの解析版で利用できません。指標を確認して選択してください。</p>:metric!==revision.config.plan_resolution.metric?<p className={styles.notice}>採用計画から指標を変更しています。この選択を統計条件として保存します。</p>:null)}
   <label>統計モデル<select aria-label="統計モデル" value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value!=="experimental-unit"&&kind==="paired")setKind("distribution");}}><option value="experimental-unit">独立実験単位での比較</option><option value="exploratory" disabled={!canGfpRelate}>GFP・撮影日を調整する探索的回帰</option></select></label>
   {mode==="experimental-unit"?<><label>条件間の対応<select aria-label="条件間の対応" value={design} onChange={e=>{setDesign(e.target.value);setConfirmed(false);if(e.target.value!=="paired"&&kind==="paired")setKind("distribution");}}><option value="unselected">実験の組み方から選択してください</option><option value="independent">別々の独立試料を各群に割り付けた</option><option value="paired">同じ個体・対応する試料を両条件で測った</option></select></label><p className={styles.small}>{design==="unselected"?"細胞数や撮影日から対応関係を推定しません。処置を割り付けた単位を確認してください。":paired?"対応ありt検定：両群の同じ個体・対応する試料に同一ペアIDを使います。":"対応なし：Welch t検定。群間で同じ独立単位を共有できません。"}<br/>視野内中央値 → 試料内視野平均 → 独立単位内試料平均。</p><label className={styles.checkbox}><input type="checkbox" checked={confirmed} disabled={design==="unselected"} onChange={e=>setConfirmed(e.target.checked)}/>独立実験単位と対応関係を確認しました。</label></>:<><div className={styles.notice}>視野クラスタ標準誤差による探索解析です。同じ生物学的単位に属する複数視野の依存までは補正しません。群と撮影日の交絡・少数クラスタも確認します。GFP量による調整は、処置の総効果とは異なる関係を推定する場合があります。</div><label>GFP変換<select aria-label="GFP変換" value={transform} onChange={e=>setTransform(e.target.value)}><option value="positive-log2">正の背景補正値のlog₂</option><option value="legacy-log2p1">互換：log₂(max(GFP,0)+1)</option></select></label></>}
   <label>基準群<select aria-label="基準群" value={baseline} onChange={e=>{setBaseline(e.target.value);setTargets(groups.filter(g=>g!==e.target.value));}}>{groups.map(g=><option key={g}>{g}</option>)}</select></label>
   <label>Holm補正の比較集合<select aria-label="Holm補正の比較集合" value={family} onChange={e=>setFamily(e.target.value)}><option value="baseline">基準群との比較</option><option value="repeat">リピート群間の比較</option><option value="all">事前指定した比較</option></select></label>
   {family==="baseline"?<fieldset className={styles.targetGroups}><legend>比較する群</legend>{groups.filter(g=>g!==baseline).map(g=><label className={styles.checkbox} key={g}><input type="checkbox" checked={targets.includes(g)} onChange={e=>setTargets(prev=>e.target.checked?[...prev,g]:prev.filter(x=>x!==g))}/>{g}</label>)}</fieldset>:<label>比較ペア（1行に「群A,群B」）<textarea rows={3} value={customComparisons} onChange={e=>setCustomComparisons(e.target.value)}/></label>}
   {source==="images"&&<details><summary>感度解析</summary>{hasGfp&&source==="images"&&<label>事前指定のGFP閾値（カンマ区切り）<input value={thresholds} onChange={e=>setThresholds(e.target.value)} placeholder="例：100,200,300"/></label>}<label className={styles.checkbox}><input type="checkbox" checked={completeDates} onChange={e=>setCompleteDates(e.target.checked)}/>比較群が揃った撮影日のみでも再解析</label>{revision?.config.recipe.id==="ncl-legacy-rgb"&&<fieldset className={styles.targetGroups}><legend>NCL高輝度領域の感度解析</legend>{[5,10,20].map(value=><label className={styles.checkbox} key={value}><input type="checkbox" checked={highRegions.includes(value)} onChange={e=>setHighRegions(values=>e.target.checked?[...values,value]:values.filter(x=>x!==value))}/>核内上位 {value}%</label>)}</fieldset>}{revision?.config.recipe.id==="ncl-native-2d"&&<fieldset className={styles.targetGroups}><legend>別の核小体領域定義で再測定した版</legend>{alternateRegions.length?alternateRegions.map(r=><label key={r.id} className={styles.checkbox}><input type="checkbox" checked={regionRevisions.includes(r.id)} onChange={e=>setRegionRevisions(values=>e.target.checked?[...values,r.id]:values.filter(id=>id!==r.id))}/>解析版 {revisions.findIndex(v=>v.id===r.id)+1}（{r.id.slice(0,8)}） · {r.config.recipe.nucleolar_method} · σ {r.config.recipe.smoothing_sigma_px} · 最小 {r.config.recipe.minimum_area_px} px²</label>):<p className={styles.small}>品質確認済みの別の解析版が必要です。</p>}<p className={styles.small}>原画像・核・背景・除外・GFP選別が同じ版を比較します。条件の一致は実行時に検証します。</p></fieldset>}<p className={styles.small}>有意差を得るための自動閾値探索は行いません。別の領域定義は新しい解析版として再測定してください。</p></details>}
   <hr/><h3>図の出力設定</h3><div className={styles.formGrid}><label>図の種類<select aria-label="図の種類" value={kind} onChange={e=>setKind(e.target.value)}><option value="distribution">群別分布・反復単位</option><option value="scatter" disabled={!canGfpRelate}>GFP散布図{mode==="exploratory"?"・調整回帰":"（観測点）"}</option><option value="paired" disabled={!paired||mode!=="experimental-unit"}>対応ありの図</option></select></label><label>ラベル言語<select aria-label="ラベル言語" value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="ja">日本語</option></select></label></div>
   <label>図のサイズ<select aria-label="図のサイズ" value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value!=="custom"){setFont(7);setHeight(3);}}}><option value="nature-single">Nature · 1段幅 89 mm</option><option value="nature-double">Nature · 2段幅 183 mm</option><option value="custom">カスタム</option></select></label><div className={styles.formGrid}>{preset==="custom"&&<label>幅 / inch<input type="number" min={3} max={16} step=".1" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label>}<label>高さ / inch<input type="number" min={1} max={preset==="custom"?16:170/25.4} step=".1" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>文字 / pt<input type="number" min={5} max={preset==="custom"?24:7} value={font} onChange={e=>setFont(Number(e.target.value))}/></label></div><p className={styles.small}>寸法と文字サイズのプリセットです。投稿規定の全項目への適合や、解析の妥当性を保証するものではありません。</p>
   <label>横軸ラベル（任意）<input value={xLabel} onChange={e=>setXLabel(e.target.value)} maxLength={120}/></label><label>縦軸ラベル（任意）<input value={yLabel} onChange={e=>setYLabel(e.target.value)} maxLength={120}/></label><label>群の表示順（カンマ区切り・任意）<input value={order} onChange={e=>setOrder(e.target.value)}/></label>
   <button className={styles.primary} disabled={blocked||(source==="images"&&(!revision?.reviewed||dirty||!metricIds.includes(metric)))||!baseline||(mode==="experimental-unit"&&(!confirmed||design==="unselected"))} onClick={()=>run(generate)}>統計と図を生成</button>
   {source==="images"&&!revision?.reviewed&&<p className={styles.small}>先に画像と領域タブで品質確認を完了してください。</p>}
  </div>
  <div className={styles.statsResults}>{!job?<div className={styles.emptyWorkspace}><h2>統計結果は未作成です</h2><p>指標・実験単位・比較条件を指定して実行してください。</p></div>:<><div className={styles.sectionHeader}><h2>統計結果</h2><label>出力履歴<select value={job.id} onChange={e=>setSelectedJob(e.target.value)}>{available.map(j=><option key={j.id} value={j.id}>{new Date(j.created*1000).toLocaleString("ja-JP")} {j.revision_id!==revision?.id?"（旧版／数値表）":""}</option>)}</select></label></div>
   {source==="images"&&job.revision_id!==revision?.id&&<div className={styles.notice}>この図は採用中の画像解析版とは別の解析版、または数値表から作成されています。保存する前に参照元を確認してください。</div>}
   <ResultWarnings warnings={result.data?.warnings}/>
   <div className={styles.countCards}>{result.data?.counts.map((c,i)=><div key={i}><b>{String(c.condition)}</b><span><strong>{String(c.experimental_units)}</strong> 独立単位</span><small>{String(c.fields)} 視野 · {String(c.cells??c.observations)} 細胞／測定値</small></div>)}</div>
   <div className={styles.figure}>{image?<img src={image} alt="保存された測定表から生成した統計図"/>:<p>図を読み込み中…</p>}</div>
   <div className={styles.downloadBar}>{["svg","pdf","png"].map(ext=><button key={ext} className={styles.secondary} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/figure.${ext}`,`cytellect-figure.${ext}`))}>{ext.toUpperCase()} ↓</button>)}{["plot-data.csv","comparisons.csv","experimental-units.csv","field-summary.csv","figure-data.json","figure-caption.md",...(result.data?.model?["model-predictions.csv","model-coefficients.csv","repeat-trend.csv"]:[]),...(result.data?.sensitivities?.length?["sensitivity-comparisons.csv","sensitivity-counts.csv","sensitivity-status.csv"]:[])].map(file=><button key={file} className={styles.linkButton} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/${file}`,file))}>{file} ↓</button>)}</div>
   {job.kind==="table-statistics"&&<div className={styles.downloadBar}><button className={styles.secondary} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/analysis.zip`,"cytellect-table-analysis.zip"))}>数値表の再実行パッケージ ↓</button><button className={styles.linkButton} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/methods.md`,"methods.md"))}>Methods ↓</button><p className={styles.small}>元のCSVは含みません。再実行時には、お手元の元CSVを指定してください。</p></div>}
   <div className={styles.card}><h3>事前指定比較</h3><ComparisonTable rows={result.data?.comparisons||[]}/></div>
   {result.data&&<ModelResult result={result.data}/>}
   {!!result.data?.sensitivities?.length&&<SensitivityResults items={result.data.sensitivities}/>}
  </>}</div>
 </section>;
}
