"use client";
import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { download, post, request } from "@/lib/api";
import { usePrivateImage } from "@/lib/usePrivateImage";
import { formatValue, metricLabels, type Field, type Job, type Revision } from "@/lib/types";
import styles from "./workspace.module.css";
type Result={counts:Record<string,unknown>[];comparisons:Record<string,unknown>[];warnings:string[];means:Record<string,unknown>[];sensitivities?:Array<{scenario:string;status:string;reason?:string}>;model?:unknown};
type NumericTable={id:string;row_count:number;metadata:{groups?:string[];conditions?:string[]}};
type Props={wid:string;revision?:Revision;jobs:Job[];fields:Field[];dirty:boolean;blocked:boolean;run:(fn:()=>Promise<void>)=>void};
export default function StatisticsPanel({wid,revision,jobs,fields,dirty,blocked,run}:Props){
 const qc=useQueryClient();
 const [metric,setMetric]=useState("ncl_log2_nucleoplasm_over_nucleoli");const [mode,setMode]=useState("experimental-unit");const [paired,setPaired]=useState(true);const [confirmed,setConfirmed]=useState(false);const [kind,setKind]=useState("distribution");const [language,setLanguage]=useState("en");const [baseline,setBaseline]=useState("");const [targets,setTargets]=useState<string[]>([]);const [family,setFamily]=useState("baseline");const [customComparisons,setCustomComparisons]=useState("");const [selectedJob,setSelectedJob]=useState("");
 const [highRegions,setHighRegions]=useState<number[]>([]);const [width,setWidth]=useState(7);const [height,setHeight]=useState(5);const [font,setFont]=useState(10);const [xLabel,setXLabel]=useState("");const [yLabel,setYLabel]=useState("");const [order,setOrder]=useState("");const [thresholds,setThresholds]=useState("");const [completeDates,setCompleteDates]=useState(false);const [transform,setTransform]=useState("positive-log2");const [source,setSource]=useState("images");
 const tables=useQuery({queryKey:["tables",wid],queryFn:()=>request<NumericTable[]>(`/v1/workspaces/${wid}/tables`)});
 const table=tables.data?.find(t=>t.id===source);
 const groups=useMemo(()=>source==="images"?[...new Set(fields.map(f=>f.metadata.condition))]:table?.metadata?.groups||table?.metadata?.conditions||[],[source,fields,table]);
 useEffect(()=>{setBaseline(groups[0]||"");setTargets(groups.slice(1));},[groups]);
 useEffect(()=>{if(revision?.config.recipe.id==="ncl-legacy-rgb"){setMetric("ncl_legacy_release");setTransform("legacy-log2p1");}},[revision?.config.recipe.id]);
 const available=jobs.filter(j=>["statistics","table-statistics"].includes(j.kind)&&j.state==="succeeded").toSorted((a,b)=>b.created-a.created);
 const job=available.find(j=>j.id===selectedJob)||available.find(j=>j.revision_id===revision?.id)||available[0];
 const result=useQuery({queryKey:["statistics",job?.id],queryFn:()=>request<Result>(`/v1/jobs/${job!.id}/result`),enabled:!!job});
 const image=usePrivateImage(job?`/v1/jobs/${job.id}/files/figure.png`:null);
 async function generate(){
  const comparisons=family==="baseline"?targets.map(target=>[baseline,target]):customComparisons.split("\n").filter(v=>v.trim()).map(v=>v.split(",").map(x=>x.trim()));
  const body={metric:source==="images"?metric:"value",mode,baseline,comparisons,paired,independent_units_confirmed:confirmed,comparison_family:family,gfp_transform:transform,sensitivity_gfp_thresholds:thresholds.trim()?thresholds.split(",").map(Number):[],sensitivity_complete_dates:completeDates,sensitivity_legacy_high_regions:highRegions,plot:{kind,language,width_inches:width,height_inches:height,font_size:font,x_label:xLabel,y_label:yLabel,group_order:order.trim()?order.split(",").map(v=>v.trim()):[]}};
  const response=await post<{job_id:string}>(source==="images"?`/v1/revisions/${revision!.id}/statistics`:`/v1/tables/${source}/statistics`,body);setSelectedJob(response.job_id);
 }
 const warnings:Record<string,string>={few_clusters_inference_unreliable:"クラスタ数が少ないため、推論の信頼性に制約があります。",exploratory_cell_level_inference:"細胞単位の探索解析です。独立反復に基づく確認的な結論として扱わないでください。"};
 return <section className={styles.statistics}>
  <div className={styles.statsControls}><span className={styles.sectionNumber}>STATISTICS & FIGURES</span><h2>比較の単位を確かめる</h2><p className={styles.small}>細胞数、視野数、独立実験単位数を区別します。撮影日と独立実験単位は同じ意味ではありません。</p>
   <label>解析するデータ<select value={source} onChange={e=>setSource(e.target.value)}><option value="images">採用中の画像解析版</option>{tables.data?.map((t,i)=><option value={t.id} key={t.id}>数値表 {i+1} · {t.row_count} 行</option>)}</select></label>
   <details className={styles.numericImport}><summary>測定済み数値CSVを取り込む</summary><p className={styles.small}>RNA・DNAなどの測定済み値を比較します。必要列：condition, experimental_unit, sample, field_id, acquisition_date, value。任意列：pair, repeat_length。装置固有の前処理は行いません。</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);run(async()=>{const r=await request<{table_id:string}>(`/v1/workspaces/${wid}/tables`,{method:"POST",body:data});await qc.invalidateQueries({queryKey:["tables",wid]});setSource(r.table_id);form.reset();});}}><label>数値CSV<input type="file" name="file" accept=".csv" required/></label><button className={styles.secondary} disabled={blocked}>数値表を登録</button></form></details>
   {source==="images"&&<label>指標<select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(metricLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>}
   <label>統計モデル<select value={mode} onChange={e=>setMode(e.target.value)}><option value="experimental-unit">独立実験単位での比較</option><option value="exploratory" disabled={source!=="images"}>GFP・撮影日を調整する探索的回帰</option></select></label>
   {mode==="experimental-unit"?<><label className={styles.checkbox}><input type="checkbox" checked={paired} onChange={e=>setPaired(e.target.checked)}/>対応ありt検定（ペアIDを使用）</label><p className={styles.small}>{paired?"各群の独立単位を同一ペアIDで対応させます。":"対応なし：Welch t検定。群間で同じ独立単位を共有できません。"}<br/>視野内中央値 → 試料内視野平均 → 独立単位内試料平均。</p><label className={styles.checkbox}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>独立実験単位と対応関係を確認しました。</label></>:<><div className={styles.notice}>視野クラスタ標準誤差による探索解析です。群と撮影日の交絡や少数クラスタを確認します。</div><label>GFP変換<select value={transform} onChange={e=>setTransform(e.target.value)}><option value="positive-log2">正の背景補正値のlog₂</option><option value="legacy-log2p1">互換：log₂(max(GFP,0)+1)</option></select></label></>}
   <label>基準群<select value={baseline} onChange={e=>{setBaseline(e.target.value);setTargets(groups.filter(g=>g!==e.target.value));}}>{groups.map(g=><option key={g}>{g}</option>)}</select></label>
   <label>Holm補正の比較集合<select value={family} onChange={e=>setFamily(e.target.value)}><option value="baseline">基準群との比較</option><option value="repeat">リピート群間の比較</option><option value="all">事前指定した比較</option></select></label>
   {family==="baseline"?<fieldset className={styles.targetGroups}><legend>比較する群</legend>{groups.filter(g=>g!==baseline).map(g=><label className={styles.checkbox} key={g}><input type="checkbox" checked={targets.includes(g)} onChange={e=>setTargets(prev=>e.target.checked?[...prev,g]:prev.filter(x=>x!==g))}/>{g}</label>)}</fieldset>:<label>比較ペア（1行に「群A,群B」）<textarea rows={3} value={customComparisons} onChange={e=>setCustomComparisons(e.target.value)}/></label>}
   <details><summary>感度解析</summary><label>事前指定のGFP閾値（カンマ区切り）<input value={thresholds} onChange={e=>setThresholds(e.target.value)} placeholder="例：100,200,300"/></label><label className={styles.checkbox}><input type="checkbox" checked={completeDates} onChange={e=>setCompleteDates(e.target.checked)}/>比較群が揃った撮影日のみでも再解析</label>{revision?.config.recipe.id==="ncl-legacy-rgb"&&<fieldset className={styles.targetGroups}><legend>NCL高輝度領域の感度解析</legend>{[5,10,20].map(value=><label className={styles.checkbox} key={value}><input type="checkbox" checked={highRegions.includes(value)} onChange={e=>setHighRegions(values=>e.target.checked?[...values,value]:values.filter(x=>x!==value))}/>核内上位 {value}%</label>)}</fieldset>}<p className={styles.small}>有意差を得るための自動閾値探索は行いません。別の領域定義は新しい解析版として再測定してください。</p></details>
   <hr/><h3>図の設定</h3><div className={styles.formGrid}><label>図の種類<select value={kind} onChange={e=>setKind(e.target.value)}><option value="distribution">群別分布・反復単位</option><option value="scatter">GFP散布図・回帰</option><option value="paired">対応ありの図</option></select></label><label>ラベル言語<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="ja">日本語</option></select></label></div>
   <div className={styles.formGrid}><label>幅 / inch<input type="number" min={3} max={16} step=".5" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><label>高さ / inch<input type="number" min={3} max={16} step=".5" value={height} onChange={e=>setHeight(Number(e.target.value))}/></label><label>文字 / pt<input type="number" min={6} max={24} value={font} onChange={e=>setFont(Number(e.target.value))}/></label></div>
   <label>横軸ラベル（任意）<input value={xLabel} onChange={e=>setXLabel(e.target.value)} maxLength={120}/></label><label>縦軸ラベル（任意）<input value={yLabel} onChange={e=>setYLabel(e.target.value)} maxLength={120}/></label><label>群の表示順（カンマ区切り・任意）<input value={order} onChange={e=>setOrder(e.target.value)}/></label>
   <button className={styles.primary} disabled={blocked||(source==="images"&&(!revision?.reviewed||dirty))||!baseline||(mode==="experimental-unit"&&!confirmed)} onClick={()=>run(generate)}>統計と図を生成</button>
   {source==="images"&&!revision?.reviewed&&<p className={styles.small}>先に画像と領域タブで品質確認を完了してください。</p>}
  </div>
  <div className={styles.statsResults}>{!job?<div className={styles.emptyWorkspace}><span className={styles.emptyIcon}>↗</span><h2>数値の背景まで、伝わる図へ。</h2><p>解析単位と比較を指定すると、測定表と紐づいた<br/>編集可能な図を生成します。</p></div>:<><div className={styles.sectionHeader}><h2>統計結果</h2><label>出力履歴<select value={job.id} onChange={e=>setSelectedJob(e.target.value)}>{available.map(j=><option key={j.id} value={j.id}>{new Date(j.created*1000).toLocaleString("ja-JP")} {j.revision_id!==revision?.id?"（旧版／数値表）":""}</option>)}</select></label></div>
   {job.revision_id!==revision?.id&&<div className={styles.notice}>この図は採用中の画像解析版とは別の解析版、または数値表から作成されています。保存する前に参照元を確認してください。</div>}
   {result.data?.warnings.map((w,i)=><div key={i} className={styles.notice}>{warnings[w]||w}</div>)}
   <div className={styles.countCards}>{result.data?.counts.map((c,i)=><div key={i}><b>{String(c.condition)}</b><span><strong>{String(c.experimental_units)}</strong> 独立単位</span><small>{String(c.fields)} 視野 · {String(c.cells??c.observations)} 細胞／測定値</small></div>)}</div>
   <div className={styles.figure}>{image?<img src={image} alt="保存された測定表から生成した統計図"/>:<p>図を読み込み中…</p>}</div>
   <div className={styles.downloadBar}>{["svg","pdf","png"].map(ext=><button key={ext} className={styles.secondary} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/figure.${ext}`,`cytellect-figure.${ext}`))}>{ext.toUpperCase()} ↓</button>)}{["plot-data.csv","comparisons.csv","experimental-units.csv"].map(file=><button key={file} className={styles.linkButton} onClick={()=>run(()=>download(`/v1/jobs/${job.id}/files/${file}`,file))}>{file} ↓</button>)}</div>
   <div className={styles.card}><h3>事前指定比較</h3><div className={styles.tableWrap}><table><thead><tr><th>群A</th><th>群B</th><th>差</th><th>95% CI</th><th>p</th><th>Holm調整p</th></tr></thead><tbody>{result.data?.comparisons.map((c,i)=><tr key={i}><td>{String(c.group_a)}</td><td>{String(c.group_b)}</td><td>{formatValue(c.estimate)}</td><td>{formatValue(c.ci_low)} – {formatValue(c.ci_high)}</td><td>{formatValue(c.p_value)}</td><td>{formatValue(c.p_holm)}</td></tr>)}</tbody></table></div></div>
   {!!result.data?.sensitivities?.length&&<div className={styles.card}><h3>感度解析</h3>{result.data.sensitivities.map((s,i)=><p key={i}>{s.scenario}：{s.status} {s.reason||""}</p>)}</div>}
  </>}</div>
 </section>;
}
