"use client";
import dynamic from "next/dynamic";
import { useEffect, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { request, post, errorMessage, errorCodeMessage, download } from "@/lib/api";
import { defaultRecipe, fieldRoles, formatValue, qualityReasonLabel, type Background, type Config, type Field, type Job, type Layer, type Masks, type Measurements, type Operation, type Point, type Revision, type Session, type Workspace } from "@/lib/types";
import { RevisionNavigation } from "@/lib/revision-navigation";
import { signalQualityItems } from "@/lib/signal-quality";
import { analysisSubmission, missingBackgroundFields, sameRecipe, type AnalysisScope } from "@/lib/analysis-submission";
import type { Cell } from "@/lib/types";
import UploadPanel from "./UploadPanel";
import StatisticsPanel from "./StatisticsPanel";
import styles from "./workspace.module.css";
const FieldCanvas=dynamic(()=>import("./FieldCanvas"),{ssr:false,loading:()=> <div className={styles.canvasLoading}>ビューアを準備しています…</div>});
const operationNames:Record<Operation,string>={select:"選択",background:"背景ROI",add:"追加",replace:"輪郭修正",delete:"削除",merge:"結合",split:"分割"};
type Props={id:string;session:Session;onBack:()=>void;onError:(error:string)=>void};
function SignalQuality({cell}:{cell:Cell}){
 const items=signalQualityItems(cell);
 if(!items.length)return null;
 return <details data-testid="signal-quality"><summary>{items.some(item=>item.weak)?"弱い信号・要確認":"信号 / 背景ばらつき"}</summary>{items.map(item=><div key={item.prefix}><b>{item.label}</b> {item.value}<small> · {item.reason}</small></div>)}</details>;
}
export default function Workbench({id,session,onBack,onError}:Props){
 const qc=useQueryClient();const loadedRevision=useRef<string | undefined>(undefined);const [navigation,setNavigation]=useState(()=>new RevisionNavigation());const [busy,setBusy]=useState(false);const [fieldId,setFieldId]=useState("");const [tab,setTab]=useState("analysis");
 const [config,setConfig]=useState<Config>({recipe:{...defaultRecipe},backgrounds:{},exclusions:[]});const [dirty,setDirty]=useState(false);
 const [layer,setLayer]=useState<Layer>("nuclei");const [operation,setOperation]=useState<Operation>("select");const [selected,setSelected]=useState<number[]>([]);const [polygon,setPolygon]=useState<Point[]>([]);
 const [parent,setParent]=useState("");const [channel,setChannel]=useState("merge");const [gain,setGain]=useState(1);const [showMasks,setShowMasks]=useState(true);const [coordinates,setCoordinates]=useState("");
 const [ackInvalidated,setAckInvalidated]=useState(false);const [includeRaw,setIncludeRaw]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [reviewConfirmed,setReviewConfirmed]=useState(false);const [excludeReason,setExcludeReason]=useState("");
 const [pendingDetection,setPendingDetection]=useState<AnalysisScope|null>(null);const controlsRef=useRef<HTMLElement>(null);const measurementsRef=useRef<HTMLElement>(null);const editorRef=useRef<HTMLDivElement>(null);
 const space=useQuery({queryKey:["workspace",id],queryFn:()=>request<Workspace>(`/v1/workspaces/${id}`)});
 const fields=useQuery({queryKey:["fields",id],queryFn:()=>request<Field[]>(`/v1/workspaces/${id}/fields`)});
 const revisions=useQuery({queryKey:["revisions",id],queryFn:()=>request<Revision[]>(`/v1/workspaces/${id}/revisions`)});
 const jobs=useQuery({queryKey:["jobs",id],queryFn:()=>request<Job[]>(`/v1/workspaces/${id}/jobs`),refetchInterval:q=>q.state.data?.some(j=>["running","queued"].includes(j.state))?1500:false});
 const active=(revisions.data||[]).find(r=>r.id===space.data?.active_revision);const fid=fieldId||fields.data?.[0]?.id||"";const field=fields.data?.find(f=>f.id===fid);
 const roles=fieldRoles(field);const hasNcl=roles.includes("ncl");const hasGfp=roles.includes("gfp");const nucleolarRecipe=config.recipe.id!=="gfp-nuclear-2d";
 const previewChannel=channel==="merge"||roles.includes(channel)?channel:"merge";
 const running=jobs.data?.some(j=>["running","queued"].includes(j.state));
 const masks=useQuery({queryKey:["masks",active?.id,fid],queryFn:()=>request<Masks>(`/v1/revisions/${active!.id}/fields/${fid}/masks`),enabled:!!fid&&active?.state==="succeeded"&&!!active.config.field_ids?.includes(fid)});
 const measured=useQuery({queryKey:["measurements",active?.id],queryFn:()=>request<Measurements>(`/v1/revisions/${active!.id}/measurements`),enabled:active?.state==="succeeded"});
 const statusKey=(jobs.data||[]).map(j=>j.id+j.state).join("|");
 useEffect(()=>{void qc.invalidateQueries({queryKey:["workspace",id]});void qc.invalidateQueries({queryKey:["revisions",id]});},[statusKey,qc,id]);
 useEffect(()=>{if(active && loadedRevision.current !== active.id){loadedRevision.current=active.id;setConfig({recipe:{...defaultRecipe,...active.config.recipe},backgrounds:active.config.backgrounds,exclusions:active.config.exclusions});setDirty(false);setReviewConfirmed(false);setAckInvalidated(false);setPendingDetection(null);}},[active]); // A scientific revision is immutable.
 useEffect(()=>{setSelected([]);setPolygon([]);setCoordinates("");setPendingDetection(null);},[fid,layer,operation]);
 useEffect(()=>{if(!hasNcl||!nucleolarRecipe)setLayer("nuclei");},[hasNcl,nucleolarRecipe]);
 async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:["workspace",id]}),qc.invalidateQueries({queryKey:["revisions",id]}),qc.invalidateQueries({queryKey:["jobs",id]}),qc.invalidateQueries({queryKey:["fields",id]})]);}
 async function act(fn:()=>Promise<void>){onError("");setBusy(true);try{await fn();await refresh();}catch(e){onError(errorMessage(e));}finally{setBusy(false);}}
 const run=(fn:()=>Promise<void>)=>{void act(fn);};
 function change(next:Partial<Config>){setConfig(c=>({...c,...next}));setDirty(true);setPendingDetection(null);}
 function background(value:Background){change({backgrounds:{...config.backgrounds,[fid]:value}});}
 async function setCurrent(rid:string){await post(`/v1/workspaces/${id}/current`,{revision_id:rid});setNavigation(n=>n.selected(active,rid));}
 const sorted=(revisions.data||[]).toSorted((a,b)=>a.created-b.created);const currentIndex=sorted.findIndex(r=>r.id===active?.id);const child=navigation.redo(sorted,active);
 const onExport=()=>run(async()=>{await post(`/v1/revisions/${active!.id}/export?include_raw=${includeRaw}`);});
 const completedExports=(jobs.data||[]).filter(j=>j.kind==="export"&&j.state==="succeeded").toSorted((a,b)=>b.created-a.created);
 const blocked=busy||!!running;
 const fieldCells=(measured.data?.cells||[]).filter(c=>c.field_id===fid);
 const failures=measured.data?.field_failures||[];const invalidated=measured.data?.invalidated_nucleoli||[];const nucleolarFailures=(measured.data?.nucleolar_failures||[]).filter(f=>!config.exclusions.some(e=>e.field_id===f.field_id&&(e.nucleus_id===null||e.nucleus_id===f.nucleus_id)&&!!e.reason.trim()));
 const recipeChanged=!!active&&!sameRecipe(config.recipe,active.config.recipe);
 const resegmentFields=recipeChanged?active?.config.field_ids||[]:[...new Set([...invalidated,...nucleolarFailures.map(f=>f.field_id)])];
 const backgroundsReady=(fields.data||[]).filter(f=>config.backgrounds[f.id]?.confirmed).length;
 const allFieldIds=(fields.data||[]).map(f=>f.id);const missingBackgrounds=missingBackgroundFields(config,allFieldIds);const trialBackgroundMissing=missingBackgroundFields(config,[fid]).length>0;
 const batchPlan=analysisSubmission(config,active,allFieldIds,"batch",fid);const pendingPlan=pendingDetection?analysisSubmission(config,active,allFieldIds,pendingDetection,fid):null;
 const unprocessedFields=allFieldIds.filter(fieldId=>!active?.config.field_ids?.includes(fieldId));
 async function startAnalysis(scope:AnalysisScope,confirmed=false){
  const plan=analysisSubmission(config,active,allFieldIds,scope,fid);
  if(plan.confirmationRequired&&!confirmed){setPendingDetection(scope);return;}
  setPendingDetection(null);
  await post(`/v1/workspaces/${id}/analyses`,{...config,field_ids:plan.field_ids,reuse_revision:plan.reuse_revision});
 }
 function showBackground(fieldId:string){setFieldId(fieldId);setOperation("background");editorRef.current?.scrollIntoView({behavior:"smooth",block:"center"});}
 const nextStep: {text:string;label?:string;action?:"background"|"conditions"|"review"|"statistics"}=running?{text:"解析を実行しています。完了後に領域と測定値を確認してください。"}:missingBackgrounds.length?{text:`背景が未確認の視野が ${missingBackgrounds.length} 件あります。信号を含まない領域を指定してください。`,label:"背景を設定",action:"background"}:!active?{text:"代表視野で検出結果を確かめてから、同じ条件を全視野へ適用します。",label:"代表視野の条件へ",action:"conditions"}:active.state!=="succeeded"?{text:"解析の状態を処理履歴で確認してください。"}:dirty?{text:"変更した条件を解析版へ反映してください。領域を保持する更新か、再検出かを選べます。",label:"解析条件へ",action:"conditions"}:failures.length||nucleolarFailures.length||invalidated.length||!active.reviewed?{text:"領域・測定値と、失敗や除外の理由を確認してください。",label:"測定値と品質確認へ",action:"review"}:unprocessedFields.length?{text:`確認済み領域を保持して、残り ${unprocessedFields.length} 視野を解析できます。`,label:"一括解析の条件へ",action:"conditions"}:{text:"この解析版は品質確認済みです。統計と図表へ進めます。",label:"統計と図表へ",action:"statistics"};
 function followNextStep(){if(nextStep.action==="background")showBackground(missingBackgrounds[0]);else if(nextStep.action==="conditions")controlsRef.current?.scrollIntoView({behavior:"smooth",block:"start"});else if(nextStep.action==="review")measurementsRef.current?.scrollIntoView({behavior:"smooth",block:"start"});else if(nextStep.action==="statistics")setTab("statistics");}
 function applyPolygon(){
  if(polygon.length<3)return;
  if(operation==="background"){background({polygon,confirmed:true});setPolygon([]);return;}
  if(!active)return;
  run(async()=>{await post(`/v1/revisions/${active.id}/edits`,{field_id:fid,layer,operation,ids:selected,polygon,parent_id:parent?Number(parent):null});setPolygon([]);setSelected([]);});
 }
 function exclude(nucleusId:number|null){
  if(!excludeReason.trim()){onError("除外理由を入力してください。");return;}
  const others=config.exclusions.filter(e=>!(e.field_id===fid&&e.nucleus_id===nucleusId));
  change({exclusions:[...others,{field_id:fid,nucleus_id:nucleusId,reason:excludeReason.trim()}]});
 }
 return <main className={styles.workbench}>
  <div className={styles.workHeader}><div><button className={styles.back} onClick={onBack}>← 作業一覧</button><h1>{space.data?.title||"ワークスペース"}</h1><span className={styles.muted}>{fields.data?.length||0} 視野 · {active?`解析版 ${currentIndex+1}`:"解析前"} · {active?.reviewed?"品質確認済み":"品質確認前"}{active?.config.field_ids&&` · 解析対象 ${active.config.field_ids.length} 視野`}</span></div><div className={styles.workHeaderRight}><span className={styles.small}>有効期限 {space.data?new Date(space.data.expires*1000).toLocaleString("ja-JP"):"—"}</span><button className={styles.secondary} disabled={busy} onClick={()=>run(async()=>{await post(`/v1/workspaces/${id}/touch`);})}>保存期限を24時間延長</button></div></div>
  <nav className={styles.tabs} aria-label="解析工程"><button className={tab==="analysis"?styles.activeTab:""} onClick={()=>setTab("analysis")}>01 <b>画像と領域</b></button><button className={tab==="statistics"?styles.activeTab:""} onClick={()=>setTab("statistics")}>02 <b>統計と図表</b></button><button className={tab==="export"?styles.activeTab:""} onClick={()=>setTab("export")}>03 <b>保存と履歴</b></button><span className={styles.tabStatus}>{running?"● 解析を実行中":dirty?"● 条件に未反映の変更があります":active?.reviewed?"✓ 確認済みの解析版":"修正は新しい解析版として保存されます"}</span></nav>
  {(space.error||fields.error)&&<div className={styles.error} role="alert">{errorMessage(space.error||fields.error)}</div>}
  {tab==="analysis"&&<>
   <UploadPanel wid={id} demo={session.demo} run={run} onDone={recipeId=>{if(!fields.data?.length&&!active)change({recipe:{...config.recipe,id:recipeId}});void refresh();}}/>
   {!!fields.data?.length&&<div className={styles.nextStep} aria-label="次の操作"><p>{nextStep.text}</p>{nextStep.action&&<button className={styles.secondary} disabled={blocked} onClick={followNextStep}>{nextStep.label} →</button>}</div>}
   {!fields.data?.length?<section className={styles.emptyWorkspace}><div className={styles.emptyIcon}>◉</div><h2>画像からはじめましょう。</h2><p>チャンネル別のTIFFを登録するか、合成データで一連の操作を試せます。</p><button className={styles.primary} disabled={blocked} onClick={()=>run(async()=>{const data=await post<{field_ids:string[];background_polygon:Point[]}>(`/v1/workspaces/${id}/synthetic`);setConfig(c=>({...c,backgrounds:Object.fromEntries(data.field_ids.map(fid=>[fid,{polygon:data.background_polygon,confirmed:true}]))}));setFieldId(data.field_ids[0]);setDirty(true);})}>合成データで試す</button><p className={styles.small}>6視野 / 2群 / 3独立反復。合成画像の操作検証であり、実画像の検出性能を示しません。</p></section>:
   <div className={styles.analysisGrid}>
    <aside className={styles.fieldSidebar}><div className={styles.sidebarTitle}><b>視野</b><span>{fields.data?.length}</span></div>{fields.data?.map((f,i)=><button key={f.id} className={f.id===fid?styles.activeField:styles.field} onClick={()=>setFieldId(f.id)}><div><span className={styles.fieldNumber}>{String(i+1).padStart(2,"0")}</span><b>{f.metadata.condition}</b></div><small>{f.metadata.sample}</small><small>{f.metadata.acquisition_date} · {f.image_info.dtype}</small><div className={styles.fieldBadges}>{f.synthetic&&<span>合成</span>}<span>{config.backgrounds[f.id]?.confirmed?"背景 ✓":"背景未設定"}</span>{config.exclusions.some(e=>e.field_id===f.id&&e.nucleus_id===null)&&<span>除外予定</span>}</div></button>)}</aside>
    <section className={styles.viewer}><div className={styles.viewerToolbar}><div className={styles.segmented}>{[["merge","重ね合わせ"],["dapi","核染色"],["ncl","NCL"],["gfp","GFP"]].filter(([value])=>value==="merge"||roles.includes(value)).map(([value,label])=><button key={value} className={previewChannel===value?styles.segmentActive:""} onClick={()=>setChannel(value)}>{label}</button>)}</div><label className={styles.inlineLabel}>表示ゲイン<input aria-label="表示ゲイン" type="range" min={.1} max={5} step={.1} value={gain} onChange={e=>setGain(Number(e.target.value))}/></label><label className={styles.checkbox}><input type="checkbox" checked={showMasks} onChange={e=>setShowMasks(e.target.checked)}/>輪郭</label></div>
     {field&&<FieldCanvas fieldId={fid} shape={field.image_info.shape} masks={masks.data} layer={layer} operation={operation} selected={selected} onSelect={setSelected} polygon={polygon} onPolygon={setPolygon} background={config.backgrounds[fid]?.polygon} channel={previewChannel} gain={gain} showMasks={showMasks}/>}
     <div className={styles.editor} ref={editorRef}><div className={styles.editorTop}><label>修正対象<select aria-label="修正対象" value={layer} onChange={e=>setLayer(e.target.value as Layer)}><option value="nuclei">核</option>{hasNcl&&nucleolarRecipe&&<option value="nucleoli">核小体候補</option>}<option value="manual">手動ROI（GFPなど）</option></select></label><div className={styles.revisionButtons}><button disabled={!active?.parent_id||blocked} onClick={()=>run(()=>setCurrent(active!.parent_id!))}>↶ Undo</button><button disabled={!child||blocked} onClick={()=>run(()=>setCurrent(child!.id))}>↷ Redo</button></div></div>
      <div className={styles.toolButtons}>{(Object.entries(operationNames) as [Operation,string][]).map(([op,name])=><button key={op} className={operation===op?styles.toolActive:""} disabled={op!=="background"&&op!=="select"&&(!active||active.state!=="succeeded"||blocked)} onClick={()=>setOperation(op)}>{name}</button>)}</div>
      <p className={styles.small}>{operation==="select"?"輪郭をクリックして選択。ドラッグで移動、スクロールで拡大できます。":operation==="background"?"細胞・核を含まない背景を多角形で囲み、確定してください。":["add","replace","split"].includes(operation)?"画像をクリックして多角形の頂点を置き、確定します。座標入力でも操作できます。":"対象IDを選び、実行してください。"} 核を変更した場合、影響した核小体は再確認が必要です。</p>
      <div className={styles.formGrid}><label>対象ID（複数はカンマ区切り）<input value={selected.join(",")} onChange={e=>setSelected(e.target.value.split(",").map(v=>Number(v.trim())).filter(n=>Number.isInteger(n)&&n>0))} placeholder="例：1,2"/></label>{layer==="nucleoli"&&<label>親核ID<input type="number" min={1} value={parent} onChange={e=>setParent(e.target.value)}/></label>}</div>
      {["background","add","replace","split"].includes(operation)&&<><details><summary className={styles.small}>座標から多角形を指定</summary><label>頂点（x,y を空白または改行で区切る）<textarea value={coordinates} onChange={e=>setCoordinates(e.target.value)} placeholder="10,10 30,10 30,30 10,30" rows={2}/></label><button className={styles.secondary} onClick={()=>{const points=coordinates.trim().split(/\s+/).map(pair=>pair.split(",").map(Number));if(points.length<3||points.some(p=>p.length!==2||!p.every(Number.isFinite))){onError("3点以上の x,y 座標を入力してください。");return;}setPolygon(points as Point[]);}}>座標を反映</button></details><div className={styles.actionRow}><button className={styles.secondary} onClick={()=>setPolygon(p=>p.slice(0,-1))} disabled={!polygon.length}>頂点を戻す</button><button className={styles.secondary} onClick={()=>setPolygon([])}>クリア</button><button className={styles.primary} disabled={polygon.length<3||blocked||(operation!=="background"&&dirty)} onClick={applyPolygon}>{operation==="background"?"背景を確定":"輪郭を保存・再測定"} · {polygon.length} 点</button></div></>}
      {["delete","merge"].includes(operation)&&<button className={styles.primary} disabled={blocked||!selected.length||dirty} onClick={()=>run(async()=>{await post(`/v1/revisions/${active!.id}/edits`,{field_id:fid,layer,operation,ids:selected,polygon:[],parent_id:null});setSelected([]);})}>選択した領域を{operationNames[operation]}・再測定</button>}
     </div>
    </section>
    <aside className={styles.controlPanel} ref={controlsRef}><div className={styles.panelTitle}><span className={styles.sectionNumber}>ANALYSIS RECIPE</span><h2>解析条件</h2></div>
     <label>レシピ<select aria-label="レシピ" value={config.recipe.id} onChange={e=>change({recipe:{...config.recipe,id:e.target.value as Config["recipe"]["id"],native_signal_qc_minimum_ratio:e.target.value==="ncl-legacy-rgb"?null:config.recipe.native_signal_qc_minimum_ratio}})}><option value="ncl-native-2d">NCL · 核と核小体</option><option value="gfp-nuclear-2d">GFP · 核内輝度</option><option value="ncl-legacy-rgb">既存RGB解析の互換モード</option></select></label>
     <div className={styles.backgroundStatus}><b>背景ROI</b><span>{backgroundsReady} / {fields.data?.length} 視野確認済み</span>{config.backgrounds[fid]?.confirmed&&<small>選択中の視野：設定済み ✓</small>}</div>
     <details><summary>核検出 · StarDist設定</summary><div className={styles.formGrid}>{[["probability","確率閾値"],["nms","NMS閾値"],["percentile_low","下側percentile"],["percentile_high","上側percentile"]] .map(([key,label])=><label key={key}>{label}<input type="number" step=".01" value={config.recipe[key as keyof Config["recipe"]] as number} onChange={e=>change({recipe:{...config.recipe,[key]:Number(e.target.value)}})}/></label>)}</div><p className={styles.small}>開始値です。実験への適合は代表画像で確認してください。</p></details>
     {nucleolarRecipe&&<><label>核小体候補の定義<select value={config.recipe.nucleolar_method} onChange={e=>change({recipe:{...config.recipe,nucleolar_method:e.target.value as "ncl-otsu"|"dapi-low"}})}><option value="ncl-otsu">核内 NCL・Otsu</option><option value="dapi-low">核染色低輝度・補助方式</option></select></label>
     <div className={styles.formGrid}><label>平滑化 σ / px<input type="number" min={0} max={10} step=".1" value={config.recipe.smoothing_sigma_px} onChange={e=>change({recipe:{...config.recipe,smoothing_sigma_px:Number(e.target.value)}})}/></label><label>最小面積 / px²<input type="number" min={1} value={config.recipe.minimum_area_px} onChange={e=>change({recipe:{...config.recipe,minimum_area_px:Number(e.target.value)}})}/></label></div>
     <label className={styles.checkbox}><input type="checkbox" checked={config.recipe.split_touching} onChange={e=>change({recipe:{...config.recipe,split_touching:e.target.checked}})}/>接触した候補を分離</label></>}
     {hasGfp&&<><label>GFPによる選別<select value={config.recipe.gfp_gate} onChange={e=>change({recipe:{...config.recipe,gfp_gate:e.target.value as Config["recipe"]["gfp_gate"],gfp_threshold:["manual","negative-control"].includes(e.target.value)?(config.recipe.gfp_threshold??0):null,legacy:{...config.recipe.legacy,gfp_mode:"recipe"}}})}><option value="none">選別しない</option><option value="negative-control">陰性対照から確定した閾値</option><option value="manual">手動閾値（探索的）</option><option value="otsu-batch">撮影バッチ内Otsu（探索的）</option></select></label>
     {["manual","negative-control"].includes(config.recipe.gfp_gate)&&<label>背景補正GFP閾値<input type="number" step="any" value={config.recipe.gfp_threshold??0} onChange={e=>change({recipe:{...config.recipe,gfp_threshold:Number(e.target.value)}})}/></label>}
     {config.recipe.gfp_gate==="negative-control"&&<details open><summary>陰性対照の視野</summary>{fields.data?.map((f,i)=><label className={styles.checkbox} key={f.id}><input type="checkbox" checked={config.recipe.gfp_negative_control_fields.includes(f.id)} onChange={e=>change({recipe:{...config.recipe,gfp_negative_control_fields:e.target.checked?[...config.recipe.gfp_negative_control_fields,f.id]:config.recipe.gfp_negative_control_fields.filter(x=>x!==f.id)}})}/>視野 {i+1} · {f.metadata.condition}</label>)}<label className={styles.checkbox}><input type="checkbox" checked={config.recipe.gfp_negative_control_confirmed} onChange={e=>change({recipe:{...config.recipe,gfp_negative_control_confirmed:e.target.checked}})}/>陰性対照の分布から閾値を確認しました。</label></details>}
     <label>GFP上限（任意）<input type="number" step="any" value={config.recipe.gfp_maximum??""} onChange={e=>change({recipe:{...config.recipe,gfp_maximum:e.target.value?Number(e.target.value):null}})}/></label></>}
     {config.recipe.id!=="ncl-legacy-rgb"&&<details><summary>弱い信号の確認（任意）</summary><label>信号 / 背景ばらつきの確認閾値<input type="number" min={0} step="any" placeholder="未設定" value={config.recipe.native_signal_qc_minimum_ratio??""} onChange={e=>change({recipe:{...config.recipe,native_signal_qc_minimum_ratio:e.target.value===""?null:Number(e.target.value)}})}/></label><p className={styles.small}>背景補正平均を背景のばらつき（1.4826 × MAD）で割った値です。指定値未満を要確認と表示します。共通の推奨閾値はなく、自動除外やGFP選別には使いません。背景のばらつきが0のときは計算できません。</p></details>}
     {nucleolarRecipe&&<p className={styles.small}>NCLを用いた領域定義はNCL再分布の影響を受けます。候補がない場合、核全体に置き換えません。</p>}
     <div className={styles.analysisLaunch}>
      <button className={styles.secondary} disabled={blocked||!fid||trialBackgroundMissing} onClick={()=>run(()=>startAnalysis("trial"))}>この視野で試す</button>
      <p className={styles.small}>{trialBackgroundMissing?"選択した視野の背景を先に確認してください。":"選択中の1視野を検出します。既存の修正がある場合は再検出を確認します。"}</p>
      <button className={styles.primary} disabled={blocked||!fields.data?.length||!!missingBackgrounds.length} onClick={()=>run(()=>startAnalysis("batch"))}>条件を固定して全視野を解析</button>
      <p className={styles.small} data-testid="batch-scope">{missingBackgrounds.length?`全視野の背景確認まで、あと ${missingBackgrounds.length} 視野です。`:batchPlan.preservedCount?`${batchPlan.preservedCount} 視野の修正済み領域を保持し、残り ${batchPlan.detectedCount} 視野を検出します。背景・選別条件を含め全視野を再測定します。`:batchPlan.confirmationRequired?"解析条件が変わっています。修正済み領域を置き換える再検出には確認が必要です。":`${allFieldIds.length} 視野を同じ条件で検出・測定します。`}</p>
      {pendingDetection&&pendingPlan&&<div className={styles.redetectionConfirm} role="alert" aria-label="再検出の確認"><b>修正済み領域を置き換えて再検出</b><p>{pendingDetection==="trial"?"選択中の1視野":`全 ${allFieldIds.length} 視野`}を再検出します。保存済みの {pendingPlan.replacedCount} 視野の領域は引き継ぎません。元の版は履歴に残ります。</p><button className={styles.secondary} disabled={blocked} onClick={()=>setPendingDetection(null)}>取消</button><button className={styles.primary} disabled={blocked} onClick={()=>run(()=>startAnalysis(pendingDetection,true))}>再検出して解析</button></div>}
     </div>
     {active?.state==="succeeded"&&<button className={styles.secondary} disabled={!dirty||blocked} onClick={()=>run(async()=>{await post(`/v1/revisions/${active.id}/reconfigure`,config);})}>現在のマスクで条件を更新</button>}
     {active?.state==="succeeded"&&nucleolarRecipe&&!!resegmentFields.length&&<><button className={styles.secondary} disabled={blocked} onClick={()=>run(async()=>{await post(`/v1/revisions/${active.id}/resegment`,{field_ids:resegmentFields,recipe:config.recipe,backgrounds:config.backgrounds,exclusions:config.exclusions});})}>核小体候補を再検出 · {resegmentFields.length} 視野</button><p className={styles.small}>{recipeChanged?"変更した条件を解析版の全視野へ適用します。":"再確認待ちの視野を再検出します。"}核の修正を保持し、背景・除外の変更も反映します。核検出条件の変更は新しい全視野解析が必要です。</p></>}
     {field?.synthetic&&<div className={styles.syntheticNote}>合成画像：操作と数値の検証用です。実画像での検出性能を示すものではありません。</div>}
    </aside>
   </div>}
   {!!active&&<section className={styles.measurements} ref={measurementsRef}>
    <div className={styles.sectionHeader}><div><span className={styles.sectionNumber}>QUALITY & MEASUREMENTS</span><h2>測定値と品質確認</h2></div><span className={styles.statusPill}>{active.state==="succeeded"?`${measured.data?.cells.length??0} 核 / 解析版 ${currentIndex+1}`:active.state}</span></div>
    {measured.data?.engine_provenance?.[fid]&&<p className={styles.small}>解析記録：{measured.data.engine_provenance[fid].engine.includes("synthetic-truth")?"合成画像の既知の正解マスク":measured.data.engine_provenance[fid].engine.includes("reused")?"前の解析版のマスクを使用":measured.data.engine_provenance[fid].engine}</p>}
    {!!failures.length&&<div className={styles.error}>処理できなかった視野が {failures.length} 件あります。失敗分を黙って除外した統計は生成しません。{failures.map(f=><p key={f.field_id}>{f.field_id.slice(0,8)}：{errorCodeMessage(f.reason)}</p>)}</div>}
    {!!invalidated.length&&<div className={styles.notice}>核の修正により {invalidated.length} 視野の核小体が再確認待ちです。</div>}
    {!!nucleolarFailures.length&&<div className={styles.error}>核小体の処理に失敗した核が {nucleolarFailures.length} 個あります。核の測定値は保持しています。再検出・手動修正、または理由を記録して除外してください。</div>}
    {measured.error&&<p role="alert">{errorMessage(measured.error)}</p>}
    <div className={styles.tableWrap}><table><thead><tr><th>核ID</th><th>群</th><th>面積 px²</th>{hasNcl&&<><th>核小体数</th><th>NCL 核全体</th><th>NCL 核小体</th><th>NCL 核質</th><th>log₂比</th></>}{hasGfp&&<th>GFP 補正平均</th>}<th>品質 / 選別</th><th>除外</th></tr></thead><tbody>{fieldCells.map(c=><tr key={c.nucleus_id} className={c.excluded?styles.excludedRow:""}><td>{c.nucleus_id}</td><td>{c.condition}</td><td>{formatValue(c.nucleus_area_px)}</td>{hasNcl&&<><td>{formatValue(c.nucleolar_count)}</td><td>{formatValue(c.ncl_nucleus_mean_corrected)}</td><td>{formatValue(c.ncl_nucleoli_mean_corrected)}</td><td>{formatValue(c.ncl_nucleoplasm_mean_corrected)}</td><td>{formatValue(c.ncl_log2_nucleoplasm_over_nucleoli)}</td></>}{hasGfp&&<td>{formatValue(c.gfp_mean_corrected)}</td>}<td>{c.excluded?"除外":!hasGfp||c.gfp_positive?"採用":"GFP範囲外"}{Math.max(Number(c.dapi_saturation_fraction??0),Number(c.ncl_saturation_fraction??0),Number(c.gfp_saturation_fraction??0))>0?" / 飽和":""}{c.touches_border?" / 画像端":""}{["no_candidate","indeterminate","unclassified","review_required","none_after_edit"].includes(String(c.nucleolar_status))?` / ${qualityReasonLabel(c.nucleolar_status)}`:""}{c.ratio_missing_reason?c.ratio_missing_reason==="ncl_not_measured_recipe"||c.ratio_missing_reason==="native_ratio_not_defined_in_legacy"?`（${qualityReasonLabel(c.ratio_missing_reason)}）`:` / ${qualityReasonLabel(c.ratio_missing_reason)}`:""}<SignalQuality cell={c}/></td><td><button className={styles.linkButton} onClick={()=>exclude(c.nucleus_id)}>除外指定</button></td></tr>)}</tbody></table>{!fieldCells.length&&<p className={styles.muted}>選択した視野の測定値はまだありません。</p>}</div>
    {!!measured.data?.nucleoli?.length&&<details className={styles.measurementDetails}><summary>核小体候補ごとの測定値</summary><div className={styles.tableWrap}><table><thead><tr><th>核小体ID</th><th>親核ID</th><th>面積 px²</th><th>NCL平均（原値）</th><th>NCL平均（背景補正）</th></tr></thead><tbody>{measured.data.nucleoli.filter(c=>c.field_id===fid).map((c,i)=><tr key={i}><td>{formatValue(c.nucleolus_id)}</td><td>{formatValue(c.nucleus_id)}</td><td>{formatValue(c.area_px)}</td><td>{formatValue(c.mean)}</td><td>{formatValue(c.mean_corrected)}</td></tr>)}</tbody></table></div></details>}
    {!!measured.data?.manual_rois?.length&&<details className={styles.measurementDetails}><summary>手動ROIの測定値</summary><div className={styles.tableWrap}><table><thead><tr><th>ROI ID</th><th>面積 px²</th>{hasGfp&&<><th>GFP平均（原値）</th><th>GFP平均（背景補正）</th></>}{hasNcl&&<th>NCL平均（背景補正）</th>}</tr></thead><tbody>{measured.data.manual_rois.filter(c=>c.field_id===fid).map((c,i)=><tr key={i}><td>{formatValue(c.roi_id)}</td><td>{formatValue(c.area_px)}</td>{hasGfp&&<><td>{formatValue(c.gfp_mean)}</td><td>{formatValue(c.gfp_mean_corrected)}</td></>}{hasNcl&&<td>{formatValue(c.ncl_mean_corrected)}</td>}</tr>)}</tbody></table></div></details>}
    <div className={styles.qcActions}><label>除外理由<input value={excludeReason} onChange={e=>setExcludeReason(e.target.value)} maxLength={200} placeholder="例：撮影範囲外、領域判定困難"/></label><button className={styles.secondary} onClick={()=>exclude(null)}>この視野を除外指定</button><span>{config.exclusions.length} 件の除外指定</span></div>
    {!!config.exclusions.length&&<details><summary>除外指定の一覧</summary>{config.exclusions.map((e,i)=><div className={styles.exclusion} key={i}><span>視野 {((fields.data||[]).findIndex(f=>f.id===e.field_id)+1)} / {e.nucleus_id===null?"全体":`核 ${e.nucleus_id}`}：{e.reason}</span><button className={styles.linkButton} onClick={()=>change({exclusions:config.exclusions.filter((_,j)=>j!==i)})}>解除</button></div>)}</details>}
    {!!invalidated.length&&<label className={styles.checkbox}><input type="checkbox" checked={ackInvalidated} onChange={e=>setAckInvalidated(e.target.checked)}/>再確認待ちの視野について、手動修正した核小体／候補なしの状態を確認しました。</label>}<div className={styles.reviewBox}><label className={styles.checkbox}><input type="checkbox" checked={reviewConfirmed} onChange={e=>setReviewConfirmed(e.target.checked)}/>領域、背景、対象選別、失敗・除外理由を確認しました。</label><button className={styles.primary} disabled={blocked||dirty||!reviewConfirmed||!!failures.length||!!nucleolarFailures.length||active.state!=="succeeded"||(!!invalidated.length&&!ackInvalidated)} onClick={()=>run(async()=>{await post(`/v1/revisions/${active.id}/review`,{accept_invalidated_fields:ackInvalidated?invalidated:[]});})}>品質確認を完了</button>{dirty&&<p className={styles.small}>条件・除外の変更を解析版へ反映してから確認してください。</p>}</div>
   </section>}
  </>}
  {tab==="statistics"&&<StatisticsPanel wid={id} revision={active} jobs={jobs.data||[]} fields={fields.data||[]} revisions={sorted} dirty={dirty} run={run} blocked={blocked} onInspectField={(fieldId,revisionId)=>run(async()=>{if(active?.id!==revisionId)await setCurrent(revisionId);setFieldId(fieldId);setTab("analysis");})}/>}
  {tab==="export"&&<section className={styles.exportPage}><div className={styles.card}><span className={styles.sectionNumber}>REPRODUCIBLE OUTPUT</span><h2>解析を手元に保存</h2><p>測定表、領域マスク、ROI、条件、Methods、環境情報を再現パッケージへまとめます。</p><label className={styles.checkbox}><input type="checkbox" checked={includeRaw} onChange={e=>setIncludeRaw(e.target.checked)}/>原画像もZIPへ含める（明示的な選択）</label><button className={styles.primary} disabled={!active||active.state!=="succeeded"||blocked||dirty} onClick={onExport}>解析パッケージを生成</button>{completedExports.map(j=><div className={styles.downloadRow} key={j.id}><span>{j.revision_id===active?.id?"採用中の版":"旧版"} · {new Date(j.created*1000).toLocaleString("ja-JP")}</span><button onClick={()=>run(()=>download(`/v1/jobs/${j.id}/files/analysis.zip`,"cytellect-analysis.zip"))}>ZIPを保存 ↓</button><button onClick={()=>run(()=>download(`/v1/jobs/${j.id}/files/methods.md`,"methods.md"))}>Methods ↓</button></div>)}</div>
   <div className={styles.card}><span className={styles.sectionNumber}>ANALYSIS HISTORY</span><h2>解析版の履歴</h2><p className={styles.small}>採用する解析版を変更すると、統計・図の参照元も変わります。過去の成果物は旧版として残ります。</p>{sorted.map((r,i)=><div key={r.id} className={styles.downloadRow}><span><b>解析版 {i+1}</b> · {r.config.recipe.id} · {r.state} {r.id===active?.id?" / 採用中":""}<small>{new Date(r.created*1000).toLocaleString("ja-JP")}</small></span><button disabled={r.state!=="succeeded"||r.id===active?.id||blocked} onClick={()=>run(()=>setCurrent(r.id))}>この版を採用</button></div>)}</div>
   <div className={styles.card}><h2>作業を削除</h2><p>原画像と派生物へのアクセスを直ちに遮断し、実行中の処理を停止してから削除します。</p><label className={styles.checkbox}><input type="checkbox" checked={confirmDelete} onChange={e=>setConfirmDelete(e.target.checked)}/>必要な結果を保存しました。この作業を削除します。</label><button className={styles.danger} disabled={!confirmDelete||busy} onClick={()=>run(async()=>{await request(`/v1/workspaces/${id}`,{method:"DELETE"});qc.removeQueries({queryKey:["workspace",id]});onBack();})}>この作業を削除</button></div></section>}
  {!!jobs.data?.length&&<details className={styles.jobs}><summary>処理履歴 · {running?"実行中":"待機中"}</summary>{jobs.data.toSorted((a,b)=>b.created-a.created).map(j=><div key={j.id}><span>{({analysis:"領域・測定",statistics:"統計・作図",export:"パッケージ出力"} as Record<string,string>)[j.kind]||j.kind} / {j.state} {j.error&&`— ${errorCodeMessage(j.error)}`}</span>{["failed","cancelled"].includes(j.state)&&<button disabled={blocked} onClick={()=>run(async()=>{await post(`/v1/jobs/${j.id}/retry`);})}>再試行</button>}{["queued","running"].includes(j.state)&&<button onClick={()=>run(async()=>{await post(`/v1/jobs/${j.id}/cancel`);})}>中止</button>}</div>)}</details>}
 </main>;
}
