"use client";
import {useLayoutEffect,useRef,useState} from "react";
import {ApiError,download,errorCodeMessage,errorMessage,post,request} from "@/lib/api";
import {usePrivateImage} from "@/lib/usePrivateImage";
import {formatValue,type Job} from "@/lib/types";
import {checkedPlot,numericFigureFiles} from "./connected-results-model";
import {EditableFigure,type FigurePart} from "./EditableFigure";
import styles from "./connected-results.module.css";
import {AxisControls,axisPlotOptions,emptyAxis,type AxisState} from "./AxisControls";

interface NumericTable {table_id:string;row_count:number;metadata:{conditions:string[];unit:string;assay:string}}
interface NumericResult {table_id:string;figure:{source_files:string[];formats?:string[]};comparisons?:Array<Record<string,unknown>>}
/** Numerical assays use the existing validated CSV/experimental-unit pipeline. */
export function ConnectedCsvResults({workspace,mode,onImages}:{workspace:string;mode:"statistics"|"figure";onImages:()=>void}){
  const [table,setTable]=useState<NumericTable|null>(null),[saved,setSaved]=useState<{job:string;figureJob:string;result:NumericResult}|null>(null);
  const [baseline,setBaseline]=useState(""),[comparisons,setComparisons]=useState<string[]>([]),[paired,setPaired]=useState(false),[confirmed,setConfirmed]=useState(false);
  const [busy,setBusy]=useState(""),[error,setError]=useState("");
  const [width,setWidth]=useState(183),[height,setHeight]=useState(100),[font,setFont]=useState(7),[x,setX]=useState(""),[y,setY]=useState(""),[min,setMin]=useState(""),[max,setMax]=useState("");
  const [part,setPart]=useState<FigurePart>("figure"),[colors,setColors]=useState<Record<string,string>>({}),[legend,setLegend]=useState(true),[pointSize,setPointSize]=useState(18);
  const [groupOrder,setGroupOrder]=useState<string[]>([]),[seriesKey,setSeriesKey]=useState("");
  const groups=table?.metadata.conditions||[];const ordered=[...groupOrder.filter(key=>groups.includes(key)),...groups.filter(key=>!groupOrder.includes(key))];const activeSeries=groups.includes(seriesKey)?seriesKey:groups[0]||"";
  const [yAxis,setYAxis]=useState<AxisState>(emptyAxis);
  const outputRef=useRef<HTMLDivElement>(null),scrollPositions=useRef<Record<string,number>>({});
  useLayoutEffect(()=>{const element=outputRef.current,positions=scrollPositions.current;if(!element)return;element.scrollTop=positions[mode]??0;return()=>{positions[mode]=element.scrollTop;};},[mode]);
  const displayPlot=()=>({...checkedPlot(width,height,font,x,y,min,max),...axisPlotOptions(emptyAxis(),{...yAxis,min,max},false),point_size:pointSize,group_order:ordered,style:{version:"1.0.0" as const,series_colors:colors,show_legend:legend}});
  const lock=useRef(false);
  const failure=(cause:unknown)=>cause instanceof ApiError?errorMessage(cause):cause instanceof Error?errorCodeMessage(cause.message):"処理を完了できませんでした。";
  async function wait(id:string){for(;;){const job=await request<Job>(`/v1/jobs/${id}`);if(job.state==="succeeded")return;if(job.state==="failed"||job.state==="cancelled")throw new Error(job.error||"処理が中止されました。");await new Promise(resolve=>setTimeout(resolve,1000));}}
  async function upload(file:File){if(lock.current)return;lock.current=true;setBusy("CSV を読み込み中…");setError("");try{const body=new FormData();body.append("file",file);const result=await request<NumericTable>(`/v1/workspaces/${workspace}/tables`,{method:"POST",body});setTable(result);setSaved(null);setBaseline(result.metadata.conditions[0]||"");setComparisons([]);setConfirmed(false);setY(result.metadata.unit);}catch(cause){setError(failure(cause));}finally{lock.current=false;setBusy("");}}
  async function calculate(){if(lock.current||!table||!confirmed||!comparisons.length)return;lock.current=true;setBusy("解析中…");setError("");try{const accepted=await post<{job_id:string}>(`/v1/tables/${table.table_id}/statistics`,{metric:"value",mode:"experimental-unit",baseline,comparisons:comparisons.map(group=>[baseline,group]),paired,independent_units_confirmed:true,comparison_family:"baseline",plot:{...displayPlot(),kind:paired?"paired":"distribution"}});await wait(accepted.job_id);const result=await request<NumericResult>(`/v1/jobs/${accepted.job_id}/result`);if(result.table_id!==table.table_id)throw new Error("入力表と結果が一致しません。");setSaved({job:accepted.job_id,figureJob:accepted.job_id,result});}catch(cause){setError(failure(cause));}finally{lock.current=false;setBusy("");}}
  async function render(savePackage=false){if(lock.current||!saved)return;lock.current=true;setBusy("図を更新中…");setError("");try{const display=displayPlot();const accepted=await post<{job_id:string}>(`/v1/jobs/${saved.job}/figure-render`,{request_id:crypto.randomUUID(),plot:{...display,y_min:display.y_min??null,y_max:display.y_max??null,kind:paired?"paired":"distribution"}});await wait(accepted.job_id);const result=await request<NumericResult>(`/v1/jobs/${accepted.job_id}/figure-render`);setSaved({...saved,figureJob:accepted.job_id,result});if(savePackage){setBusy("保存ファイルを作成中…");const packaged=await post<{job_id:string}>(`/v1/jobs/${accepted.job_id}/publication-package`,{analysis_job_id:saved.job,request_id:crypto.randomUUID()});await wait(packaged.job_id);await download(`/v1/jobs/${packaged.job_id}/files/publication.zip`,"Cytellect-publication.zip");}}catch(cause){setError(failure(cause));}finally{lock.current=false;setBusy("");}}
  return <section className={styles.root} aria-label="数値表の統計解析"><div className={styles.settings}>
    <header><h2>{mode==="figure"?"グラフ":"数値表"}</h2><button onClick={onImages}>画像の測定値</button></header>
    <label>CSV を追加<input type="file" accept=".csv,text/csv" disabled={!!busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value="";}}/></label>
    {table&&<p>{table.row_count} 行 · {table.metadata.assay||"測定値"}{table.metadata.unit?` / ${table.metadata.unit}`:""}</p>}
    {mode==="statistics"?<><label>対照群<select value={baseline} onChange={event=>{setBaseline(event.target.value);setComparisons([]);setSaved(null);}}>{table?.metadata.conditions.map(group=><option key={group}>{group}</option>)}</select></label>
      <fieldset><legend>比較する群</legend>{table?.metadata.conditions.filter(group=>group!==baseline).map(group=><label key={group} className={styles.check}><input type="checkbox" checked={comparisons.includes(group)} onChange={event=>{setComparisons(previous=>event.target.checked?[...previous,group]:previous.filter(value=>value!==group));setSaved(null);}}/>{group}</label>)}</fieldset>
      <label>対応<select value={paired?"paired":"independent"} onChange={event=>{setPaired(event.target.value==="paired");setSaved(null);setConfirmed(false);}}><option value="independent">独立した実験（Welch t 検定）</option><option value="paired">対応あり（対応 t 検定）</option></select></label>
      <label className={styles.check}><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>CSV 内の独立実験単位と対応関係を確認した</label>
      <button className={styles.primary} disabled={!!busy||!table||!confirmed||!comparisons.length} onClick={()=>void calculate()}>{busy||"計算"}</button>
    </>:<><nav className={styles.figureParts} aria-label="図の設定対象">{([["figure","図"],["x","横軸"],["y","縦軸"],["series","系列"]] as const).map(([key,label])=><button key={key} aria-pressed={part===key} onClick={()=>setPart(key)}>{label}</button>)}</nav>
      {part==="x"&&<label>横軸ラベル<input value={x} onChange={event=>setX(event.target.value)}/></label>}
      {part==="y"&&<><label>縦軸ラベル<input value={y} onChange={event=>setY(event.target.value)}/></label><AxisControls axis="y" value={{...yAxis,min,max}} onChange={value=>{setYAxis(value);setMin(value.min);setMax(value.max);}}/></>}
      {part==="figure"&&<><label>幅<select value={String(width)} onChange={event=>setWidth(Number(event.target.value))}><option value="89">1段 · 89 mm</option><option value="183">2段 · 183 mm</option></select></label><label>高さ / mm<input type="number" min={25.4} max={170} value={height} onChange={event=>setHeight(Number(event.target.value))}/></label><label>文字 / pt<input type="number" value={font} onChange={event=>setFont(Number(event.target.value))}/></label><label className={styles.check}><input type="checkbox" checked={legend} onChange={event=>setLegend(event.target.checked)}/>凡例を表示</label></>}
      {part==="series"&&<><label>系列<select value={activeSeries} onChange={event=>setSeriesKey(event.target.value)}>{ordered.map(group=><option key={group}>{group}</option>)}</select></label><label>色<input type="color" value={colors[activeSeries]||"#0072b2"} onChange={event=>setColors(previous=>({...previous,[activeSeries]:event.target.value}))}/></label><label>点の大きさ<input type="number" min={1} max={400} value={pointSize} onChange={event=>setPointSize(Number(event.target.value))}/></label><div className={styles.row}>{[-1,1].map(direction=><button key={direction} onClick={()=>{const next=[...ordered],index=next.indexOf(activeSeries);if(index<0||index+direction<0||index+direction>=next.length)return;[next[index],next[index+direction]]=[next[index+direction],next[index]];setGroupOrder(next);}}>{direction<0?"前へ":"後へ"}</button>)}</div></>}
      <button disabled={!!busy||!saved} onClick={()=>void render()}>{busy||"図を更新"}</button></>}
    {error&&<p role="alert">{error}</p>}{saved&&<div className={styles.downloads}><button disabled={!!busy} onClick={()=>void render(true)}>保存</button></div>}
  </div><div className={styles.output} ref={outputRef}>{mode==="statistics"&&saved?.result.comparisons&&<div className={styles.tableScroll}><table><thead><tr><th>比較</th><th>推定値</th><th>p 値</th><th>補正 p 値</th></tr></thead><tbody>{saved.result.comparisons.map((row,index)=><tr key={index}><th>{String(row.group_a)} / {String(row.group_b)}</th><td>{formatValue(row.estimate??row.effect)}</td><td>{formatValue(row.p_value)}</td><td>{formatValue(row.p_holm??row.p_adjusted)}</td></tr>)}</tbody></table></div>}{saved?numericFigureFiles(saved.result.figure).filter(name=>name.endsWith(".svg")).map(name=>mode==="figure"?<EditableFigure key={`${saved.figureJob}:${name}`} path={`/v1/jobs/${saved.figureJob}/files/${encodeURIComponent(name)}`} onSelect={setPart}/>:<CsvFigure key={`${saved.figureJob}:${name}`} path={`/v1/jobs/${saved.figureJob}/files/${encodeURIComponent(name)}`}/>):<div className={styles.empty}><h3>測定済みの数値表から比較・作図</h3><p>画像の追加は不要です。UTF-8 の CSV を読み込みます。</p><p>必須列：condition、experimental_unit、sample、field_id、acquisition_date、value</p><p>任意列：pair、repeat_length、unit、assay</p><p>視野内中央値 → 試料平均 → 独立実験単位平均で集計し、指定した比較に Holm 補正を適用します。</p></div>}</div></section>;
}
function CsvFigure({path}:{path:string}){const url=usePrivateImage(path);return url?<img className={styles.figure} src={url} alt="数値表から作成したグラフ"/>:<p role="status">図を読み込み中…</p>;}
